// Otomatik üretildi — Müşteriler.xlsx 01.07.2026
// 1563 müşteri, 16 plasiyer

export const MUSTERI_PLASIYER: Record<string, string> = {
  "2A OTOMOTİV - ALİ RIZA SANCAK": "Seçkin Ozan Akıllı",
  "2A UYGUN OTOMOTİV İNŞAAT VE İTH. İHR. LTD.ŞTİ.": "Ferhan Demir",
  "3E YEDEK PARÇA OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Serdar Parlakkan",
  "4K ÖZTÜRK OTOMOTİV SERVİS HİZMETLERİ İNŞ.TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "4K ÖZTÜRK YEDEK PARÇA SERV.HİZM.TİC.LTD.ŞTİ. / SAN.RENAULT ŞUBE": "Ömer Kınalı",
  "4K ÖZTÜRK YEDEK PARÇA SERVİS HİZMETLERİ TİC.LTD.ŞTİ./ ŞUBE": "Ömer Kınalı",
  "5 GEN OTOMOTİV DIŞ TİCARET LTD.ŞTİ.": "Serdar Parlakkan",
  "54 GENÇLER OTOMOTİV YEDEK PARÇA SAN.TİC.LTD.ŞTİ.": "Engin Alaca",
  "A.N.S.ERCİYES OTOMOTİV MAK.MET.HUR.İNŞ.GIDA MARK.İŞLET TUR.İTH.İHRCT.SAN. VE TİC.LTD.ŞTİ.": "Engin Alaca",
  "A2A OTOMOTİV YEDEK PARÇA VE E-TİCARET LTD.ŞTİ.": "Seçkin Ozan Akıllı",
  "ABS OTOMOTIV SANAYI VE TICARET LTD STI": "Sefa Akkan",
  "ABS PLAST VACUM OTOMOTİV SAN.TİC.LTD.ŞTİ.": "Eren Aykut",
  "AC GARAGE TUNİNG OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Eren Aykut",
  "ACS OTOMOTİV VE TİCARET - SAMET SARIAYDIN": "Eren Ateş",
  "ACY OTOMOTİV YEDEK PARÇA BİLİŞİM İTHALAT İHRACAT A.Ş.": "Recep Yılmaz",
  "ADA OTOMOTİV OTO YEDEK PARÇALARI - MUSTAFA DİNEK": "Eren Ateş",
  "ADA TİCARET OTO YEDEK PARÇALARI - JAN ASARYAM": "Cüneyt Baş",
  "ADAK OTOMOTİV KORE VE JAPON OTO YEDEK PAR.-ÖNDER VOLKAN": "Ferhan Demir",
  "ADAR OTO YEDEK PARÇA SAN.VE TİC.LTD.ŞTİ.": "Onur Selvi",
  "ADEM OTOMOTİV - HÜSEYİN FERİT KOÇ": "Mustafa Koçalı",
  "ADEN OTOMOTIV YEDEK PARÇA - ERKAN ŞİMŞEK": "Recep Yılmaz",
  "ADG AUTOMOTİVE - BİLAL DOĞRU YOL": "Engin Alaca",
  "ADIGÜZEL OTO VE YEDEK PARÇA - SITKI CAN ADIGÜZEL": "Seçkin Ozan Akıllı",
  "ADIGÜZEL OTO VE YEDEK PARÇA - SITKI CAN ADIGÜZEL /2": "Seçkin Ozan Akıllı",
  "ADS GRUP OTOMOTİV YEDEK PARÇA VE TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "AFFAN OTO - AFFAN KALAYCI": "Mustafa Koçalı",
  "AFK TUNING - FERHAT KUMRAL": "Eren Aykut",
  "AG OTOMOTİV - ABDULLAH GÜNDOĞDU": "Recep Yılmaz",
  "AGG OTO YEDEK PARÇA - ALİ OSMAN GEYİK": "Serdar Parlakkan",
  "AHMET DEMİR OTO YEDEK PARÇA VE DIŞ TİC.İTH.İHR.LTD.ŞTİ.": "Alpaslan Değer",
  "AHMET MURAT KULE VE ORTAĞI": "Engin Alaca",
  "AHMET OPEL YEDEK PARÇA - AHMET KONDAKÇILAR": "Sefa Akkan",
  "AK FORD YEDEK PARÇA - ERSAN KANGIRAN": "Onur Okumuş",
  "AK OTOMOTİV OTO YEDEK PARÇALARI - MEHMET OKUKCU": "Alpaslan Değer",
  "AK YEDEK PARÇA İTH.İHR.TİC.VE SAN.LTD.ŞTİ.": "Ömer Kınalı",
  "AK İNŞAAT NAK. TAAH. BOYA SAN TİC LTD.ŞTİ.": "Alpaslan Değer",
  "AKDENİZ MERCAN OTOMOTİV YED.PAR.TUR.İNŞ.EML.NAK.İTH.İHR.TİC.LTD.ŞTİ.": "Onur Selvi",
  "AKIN OTOMOTİV ORJİNAL İTHAL YEDEK PARÇALARI - AKIN KIZILŞİMŞEK": "Engin Alaca",
  "AKMANLAR YEDEK PARÇA SAN.VE TİC.LTD.ŞTİ.": "Serdar Parlakkan",
  "AKS OTOMOTİV ORİJİNAL YEDEK PARÇALARI - EKREM KILIÇ": "Erbay Atlı",
  "AKSAM MOTOR İÇ VE DIŞ TİC.LTD.ŞTİ.": "Onur Selvi",
  "AKSAM MOTOR İÇ VE DIŞ TİCARET LTD.ŞTİ.": "Eren Ateş",
  "AKSARAY MOTORLU ARAÇLAR TİC.SAN.LTD.ŞTİ.": "Ferhan Demir",
  "AKSARAY OPEL - HARUN GENÇER": "Ferhan Demir",
  "AKSOY BİLGİ TEKNOLOJİLERİ OTOMOTİV İNŞ.SAN.TİC.LTD.ŞTİ.": "Eren Aykut",
  "AKSOY OTOMOTİV YED.PAR. - FUAT AKSOY": "Engin Alaca",
  "AKSOY OTOMOTİV YED.PAR. - MAHMUT AKSOY": "Erbay Atlı",
  "AKSOY YEDEK PARÇA TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "AKSOYLU OTO AKSESUAR SANAYİ TİCARET LİMİTED ŞİRKETİ": "Eren Aykut",
  "AKTAN OTOMOTİV - ÖMER TANRIYATAPAN": "Ferhan Demir",
  "AKTULUM OTOMOTİV İNŞ.NAK.PET.DIŞ.SAN.TİC.LTD.ŞTİ.": "Alpaslan Değer",
  "AKTİF VOLKSWAGEN ÖZEL SERVİS YEDEK PARÇA - CENGİZ İPEK": "Erbay Atlı",
  "AKYOL OTOMOTIV SAN.VE TİC.A.Ş. BOSTANCI": "Recep Yılmaz",
  "AKYOL OTOMOTIV SAN.VE TİC.A.Ş. GAZİANTEP": "Alpaslan Değer",
  "AKYOL OTOMOTİV SAN. VE TİC.A.Ş.DENİZLİ": "Onur Selvi",
  "AKYOL OTOMOTİV SAN. VE TİC.A.Ş.DEPO": "Ferhan Demir",
  "AKYOL OTOMOTİV SAN. VE TİC.A.Ş.ISPARTA": "Onur Selvi",
  "AKYOL OTOMOTİV SAN. VE TİC.A.Ş.KARTAL": "Recep Yılmaz",
  "AKYOL OTOMOTİV SAN. VE TİC.A.Ş.KAYSERİ": "Seçkin Ozan Akıllı",
  "AKYOL OTOMOTİV SAN. VE TİC.A.Ş.KONYA": "Erbay Atlı",
  "AKYOL OTOMOTİV SAN. VE TİC.A.Ş.MASLAK": "Ferhan Demir",
  "AKYOL OTOMOTİV SAN. VE TİC.A.Ş.SAKARYA": "Recep Yılmaz",
  "AKYOL OTOMOTİV SAN. VE TİC.A.Ş.TOPKAPI": "Ferhan Demir",
  "AKYOL OTOMOTİV SAN. VE TİC.A.Ş.TRABZON": "Ömer Kınalı",
  "AKYOL OTOMOTİV SAN. VE TİC.A.Ş.İKİTELLİ": "Mustafa Koçalı",
  "AKYOL OTOMOTİV SAN. VE TİC.A.Ş.İZMİR": "Sefa Akkan",
  "AKYOL OTOMOTİV SAN. VE TİC.A.Ş.İZMİT": "Recep Yılmaz",
  "AKYOL OTOMOTİV SAN.VE TİC.A.Ş. MASLAK - PERAKENDE": "Ferhan Demir",
  "AKYOL OTOMOTİV SAN.VE TİC.A.Ş.ANTALYA": "Onur Selvi",
  "AKYOL OTOMOTİV SANAYİ VE TİC.A.Ş. - AKSARAY": "Erbay Atlı",
  "AKYOL OTOMOTİV SANAYİ VE TİC.A.Ş. - AYDIN": "Sefa Akkan",
  "AKÇAY OTOMOTİV - SELAHATTİN DEMİRHAN": "Ferhan Demir",
  "AKÇE YEDEK PARÇA OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Serdar Parlakkan",
  "AKŞAN OTOMOTİV TEKEL ÜRÜNLERİ GIDA SAN.VE TİC.LTD.ŞTİ.": "Onur Selvi",
  "AL AMİN OTOMOTİV SANAYİ VE TİC. LTD. ŞTİ.": "Serdar Parlakkan",
  "ALBAY OTOMOTİV - BARIŞ ÖZTÜRK": "Recep Yılmaz",
  "ALDEMİR OTOMOTİV SAN. TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "ALEVOĞLU OTOMOTİV iNŞ. TEKS. GIDA TURZ. SAN. TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "ALFATECH OTO YEDEK PARÇA SANAYİ VE TİC.LTD.ŞTİ.": "Engin Alaca",
  "ALL PARTS OTOMOTİV VE DIŞ.TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "ALLES OTO YEDEK PARÇA SAN.VE TİC.LTD.ŞTİ.": "Ferhan Demir",
  "ALMAN CAR OTOMOTİV YED.PAR.İNŞ.PROM.İTH.İHR.LTD.ŞTİ.": "Mustafa Koçalı",
  "ALMAN GARAJ OTO YEDEK PARÇA - NECİP KAYA": "Mustafa Koçalı",
  "ALMAN OTOMOTİV - SERKAN SAKAL": "Sefa Akkan",
  "ALMER ENJEKSİYON OTO YED.PAR.SAN.VE DIŞ TİC.A.Ş.": "Cüneyt Baş",
  "ALP OTO - MEHMET ALİ ALP ÖNCÜL": "Sefa Akkan",
  "ALP PLASTİK OTO YEDEK PARÇA - ALPASLAN BAYRAKTAR": "Cüneyt Baş",
  "ALP TÜRK OTOMOTİV - NUH MEHMET KARAALP": "Seçkin Ozan Akıllı",
  "ALPAR OTO YEDEK PARÇA TEKSTİL TİCARET LİMİTED ŞİRKETİ": "Onur Selvi",
  "ALPAY MOTORLU ARAÇLAR TİCARET LTD.ŞTİ.": "Sefa Akkan",
  "ALPER OTO YEDEK PARÇA - ALPER ÖZ": "Serdar Parlakkan",
  "ALSAN GROUP MOTORLU ARAÇ.İTH.İHR.SAN.VE TİC.LTD.ŞTİ.": "Ferhan Demir",
  "ALTAN OTOM.YED. PAR. - GÜLSEVİM IŞIK": "Engin Alaca",
  "ALTEK GRUP YAPI İNŞAAT OTOMOTİV SANAYİ TİCARET VE TEKNİK KONTROL HİZMETLERİ LİMİTED ŞİRKETİ": "Eren Aykut",
  "ALTERNATİF OTOMOTIV - MEHMET TOKAK": "Alpaslan Değer",
  "ALTINOK OTOMOTİV - NECATİ EREN ALTINOK": "Eren Ateş",
  "ALTINSOY GROUP YED.PAR. - İSHAK ALTINSOY": "Erbay Atlı",
  "ALTINTAŞ OTO YEDEK PARÇA - MUHAMMET İBRAHİM ALTINTAŞ": "Ferhan Demir",
  "ALTUN OTO RADYATÖR - FETİYE ALTUN": "Ali Osman Demir",
  "ALUÇLAR OTOMOTİV İNŞ. SAN. VE TİC. LTD. ŞTİ": "Ferhan Demir",
  "ALÇAMLAR OTOMOTİV - ŞERİFE ALÇAM": "Seçkin Ozan Akıllı",
  "ALİ ALMA OTO MARKET YEDEK PARÇA SANAYİ VE TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "ALİ KOÇAK OTOMOTİV SAN.VE.TİC.LTD.ŞTİ.": "Erbay Atlı",
  "ALİ OTO": "Ferhan Demir",
  "ALİ OTOMOTİV YEDEK PARÇA - MUHAMMET ALİ ÖZTÜRK": "Recep Yılmaz",
  "ALİBO YEDEK PARÇA - FURKAN SELÇOK": "Erbay Atlı",
  "ALİN YEDEK PARÇA - ALİ ANIL TOPÇU": "Eren Ateş",
  "AMİL OTOMOTİV SANAYİ VE TİC.LTD.ŞTİ.": "Ferhan Demir",
  "ANI GROUP OTOMOTİV VE SANAYİ TİC.LTD.ŞTİ.": "Seçkin Ozan Akıllı",
  "ANIL BATMAN OTOMOTİV SANAYİ VE TİC.LTD.ŞTİ.": "Serdar Parlakkan",
  "ANKA KAYIŞ RULMAN VE OTO. YED. PARÇ. TİC. LTD. ŞTİ.": "Ferhan Demir",
  "ANKA OTOMOTİV-TÜRKAN YELİZ ÖZBOZ": "Alpaslan Değer",
  "ANKAPAR YEDEK PARÇA OTOMOTİV TİC.VE SAN.LTD.ŞTİ.": "Eren Ateş",
  "ANKARA VOLKSWAGEN - ZAFER ÇAMDİK": "Eren Ateş",
  "ANKARALILAR VOLKSWAGEN - MEHMET ERGÜN": "Erbay Atlı",
  "ANTADA OTOMOTİV SANAYİ VE TİC.LTD.ŞTİ.": "Onur Selvi",
  "ANTAL OTOMOTİV - MUSTAFA ANTAL": "Recep Yılmaz",
  "ANTALYA AKDENİZ OTO KİRALAMA YEDEK PARÇA İNŞ.TUR.İTH.İHR.VE TİC.LTD.ŞTİ.": "Onur Selvi",
  "ANTPAR OTOMOTİV YEDEK PARÇA SAN.VE TİC.LTD.ŞTİ.": "Onur Selvi",
  "ANTPAR YEDEK PARÇA - EMRAH ŞAHİN": "Onur Selvi",
  "ANTİK HASAR ONARIM MERKEZİ VE TİC. LTD. ŞTİ.": "Serdar Parlakkan",
  "ANYA MOTORLU ARAÇLAR SAN. VE TIC. LTD. STİ": "Sefa Akkan",
  "APEX CAR PARTS PAZARLAMA İTH.VE İHR.LTD.ŞTİ./ BURSA": "Engin Alaca",
  "ARBA OTOMOTİV SANAYİ VE TİCARET LTD.ŞTİ.": "Recep Yılmaz",
  "ARDIÇ OTOMOTİV SANAYİ VE TİC.LTD.ŞTİ.": "Ferhan Demir",
  "ARESS ORJINAL OTO YEDEK PARÇA LTD ŞTİ.": "Eren Ateş",
  "ARIK DİZAYN OTO AKSESUAR - HALİL ARIK": "Erbay Atlı",
  "ARKADAŞ OTO - OSMAN GÖKTÜRK": "Ferhan Demir",
  "ARKAY OTOMOTİV - SEDA YAKAR": "Ferhan Demir",
  "ARM GOKSU OTO YEDEK PARÇA SANAYİ VE TİC. LTD. ŞTİ.": "Ferhan Demir",
  "ARMA CLASS OTOMOTİV SAN VE TİC. LTD. ŞTİ.": "Onur Selvi",
  "ARS OTOMOBİL YEDEK PARÇA SAN.VE TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "ARSEL TİCARET İSMAİL YILMAZ VE ORTAĞI": "Eren Ateş",
  "ARSLANLAR OTOMOTİV İNŞ.TUR.TİC.SAN.VE LTD.ŞTİ.": "Onur Selvi",
  "ARSLANLAR OTOMOTİV İNŞ.TUR.TİC.SAN.VE LTD.ŞTİ. / ŞUBE": "Onur Selvi",
  "ARTEK MAKİNA OTO YEDEK PARÇA TİC.VE SAN.LTD.ŞTİ.": "Engin Alaca",
  "ARTI HİDROLİK DİREKSİYON OTOMOTİV VE İNŞ.LTD.ŞTİ.": "Cüneyt Baş",
  "ARTI OTO RADYATÖR - MUSTAFA KARATAŞ": "Ali Osman Demir",
  "ARTI OTOMOTİV RAMAZAN ARTVİNLİ ADİ ORTAKLIĞI": "Sefa Akkan",
  "ARZU OTOMOTİV - ABDULLAH TUNCER": "Ferhan Demir",
  "ARZUM OTO - AHMET ATALAY / ESENYURT": "Mustafa Koçalı",
  "ARZUM OTO - AHMET ATALAY / TOPKAPI": "Ferhan Demir",
  "ARZUM OTO - AHMET ATALAY / İKİTELLİ": "Mustafa Koçalı",
  "ARİSAR MOTORS EMLAK SANAYİ VE TİCARET A.Ş.": "Alpaslan Değer",
  "ASIR GIDA İNŞAAT MOBİLYA EMLAK OTOMOTİV SAN.VE TİC.LTD.ŞTİ": "Mustafa Koçalı",
  "ASLAN KARDEŞLER OTOMOTİV - FATİH ASLAN": "Ferhan Demir",
  "ASLAN KARDEŞLER OTOMOTİV VE YED.PAR.SAN.TİC.LTD.ŞTİ./ ARNAVUTKÖY": "Mustafa Koçalı",
  "ASLAN KARDEŞLER OTOMOTİV VE YEDEK PARÇA SAN.TİC.LTD.ŞTİ/SANKO": "Mustafa Koçalı",
  "ASLAN OTO YEDEK PARÇA - ORHAN ASLAN": "Mustafa Koçalı",
  "ASLAN OTOMOTİV - MURAT ASLAN": "Recep Yılmaz",
  "ASLAN OTOMOTİV - TURGAY ASLAN": "Alpaslan Değer",
  "ASLANLAR OTO YEDEK PARÇA VE AKSESUAR-ABDULKADİR ÖZASLAN": "Ferhan Demir",
  "ASLANLAR YEDEK PARÇA - RIDVAN ASLAN": "Engin Alaca",
  "ASLI OTOMOTİV TEKSTİL İNŞ. VE BİLGİSAYAR SAN.VE DIŞ TİC.LTD.ŞTİ./ İKİTELLİ": "Ferhan Demir",
  "ASPARTS OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Ferhan Demir",
  "ASPARTS OTOMOTİV SAN.VE TİC.LTD.ŞTİ. - AYDIN ELMA": "Mustafa Koçalı",
  "ASYA BİLYA YEDEK PARÇA OTOMOTİV SAN. VE TİC.LTD.ŞTİ.": "Seçkin Ozan Akıllı",
  "ASYA BİLYA YEDEK PARÇA OTOMOTİV SAN. VE TİC.LTD.ŞTİ.- ŞUBE": "Cüneyt Baş",
  "ASYILMAZ OTO - ALİ SUNAL YILMAZ": "Engin Alaca",
  "ASİLA OTOMOTİV YED.PAR.MOT.AR.TAM.BAK.SERV.TAAH.SAN.VE TİC.LTD.ŞTİ.": "Engin Alaca",
  "ASİLPAR OTOMOTİV TİCARET VE SAN.LTD.ŞTİ.": "Onur Selvi",
  "ATA OTO YEDEK PARÇA - HÜSEYİN KARAMAN": "Ömer Kınalı",
  "ATABARI OTOMOTİV TUR.PET.ÜRN.İNŞ.TAAH.NAK.TİC.VE SAN.LTD.ŞTİ.": "Engin Alaca",
  "ATACAR OTOMOTİV SAN.VE DIŞ TİC.LTD.ŞTİ.": "Ferhan Demir",
  "ATALAR OTOMOTİV - ABDÜLBAKİ BİRGÜL": "Serdar Parlakkan",
  "ATALAY OTO MARKET - AHMET ATALAY": "Onur Selvi",
  "ATALAYLAR OTO YEDEK PARÇA İNŞ.İÇ VE DIŞ TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "ATAMERT OTOMOTİV - MERTCAN HANEDAR": "Recep Yılmaz",
  "ATEŞ MOTORS OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Eren Aykut",
  "ATEŞ OTOMOTİV OPEL CHEVROLET YEDEK PARÇA - İSMAİL ATEŞ": "Seçkin Ozan Akıllı",
  "ATEŞ SERVİS YEDEK PARÇA - MURAT ATEŞ": "Onur Selvi",
  "ATEŞLER OTO RADYATÖR - ADEM ATEŞ": "Ali Osman Demir",
  "ATG OTOMOTİV - RAMAZAN ATILGAN": "Erbay Atlı",
  "ATILGAN OTO YEDEK PARÇA MAKİNA TİC.LTD.ŞTİ.": "Eren Ateş",
  "ATILIM GRUP MOT. AR. İTH. İHR. SAN. VE TİC. LTD.ŞTİ": "Eren Ateş",
  "ATİLLA OTOMOTİV - ATİLLA YAZICI": "Eren Ateş",
  "AUTO ATEŞ YEDEK PARÇA OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Serdar Parlakkan",
  "AUTO MS YEDEK PARÇA SANAYI TIC.LTD.ŞTİ": "Recep Yılmaz",
  "AUTO PARTS ENES OTOMOTİV TİC.A.Ş.": "Recep Yılmaz",
  "AUTO PRESTIGE - MAKSUT DURSUN": "Recep Yılmaz",
  "AUTO YAĞMUR OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Serdar Parlakkan",
  "AUTOTOPTAN OTOMOBİL AKS.SAN.VE TİC.LTD.ŞTİ.": "Eren Aykut",
  "AUTOWAG DIŞ TİCARET LTD.ŞTİ.": "Mustafa Koçalı",
  "AVRUPA OTOMOTİV - MURAT BOZ": "Ömer Kınalı",
  "AVŞAR OTO - SELAMİ AVŞAR": "Onur Selvi",
  "AYAR OTO OTO YEDEK PARÇA - İLYAS SAVUT": "Sefa Akkan",
  "AYAZ OTOMOTİV İÇ VE DIŞ TİCARET - FATİH KARAÇOBAN": "Recep Yılmaz",
  "AYDIN OTO - BERK AYDIN": "Sefa Akkan",
  "AYDIN OTO RADYATÖR - GÜRBÜZ AYDIN": "Ali Osman Demir",
  "AYDOĞDU OTOMOTİV - MURAT AYDOĞDU": "Seçkin Ozan Akıllı",
  "AYDOĞDU OTOMOTİV-MURAT AYDOĞDU": "Seçkin Ozan Akıllı",
  "AYFAM OTOMOTİV ORJİNAL YEDEK PARÇA - FATİH OKTAY": "Engin Alaca",
  "AYG OTOMOTİV - YASEMİN GÜNDÜZ": "Sefa Akkan",
  "AYHAN OPEL YEDEK PARÇA - ŞERİFE MADEN": "Eren Ateş",
  "AYK OTO DİZAYN SAN.VE TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "AYKOÇ OTOMOTİV İNŞ.SAN.VE TİC.LTD.ŞTİ": "Eren Ateş",
  "AYPAR OTOMOTİV YEDEK PARÇA - NURULLAH AYDIN": "Eren Ateş",
  "AZRA OTOMOTİV - CUMALİ ARSLAN": "Serdar Parlakkan",
  "AZİM OTOMOTİV İTH. VE TİC. LTD. ŞTİ.": "Cüneyt Baş",
  "AZİM OTOMOTİV İTH. VE TİC. LTD. ŞTİ. / İKİTELLİ 1": "Cüneyt Baş",
  "AĞAOĞLU YEDEK PARÇA - YASİN AĞAOĞLU / ŞUBE": "Sefa Akkan",
  "AŞKIN OTO ÖZEL SERVİS - YÜCEL YANIK": "Ömer Kınalı",
  "BAFRA OTOMOTİV -ŞİNASİ ATEŞ": "Ömer Kınalı",
  "BALCI AUTOMOTİVE TURİZM SAN.TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "BALIKESİR İNCE OTOMOTİV İNŞAAT NAKL.SAN.TİC.LTD.ŞTİ.": "Engin Alaca",
  "BALKAN RADYATÖR SAN.VE TİC.LTD. ŞTİ. / ESKİŞEHİR": "Ali Osman Demir",
  "BALKAN RADYATÖR SANAYİ VE TİC.LTD.ŞTİ./ ANKARA": "Ali Osman Demir",
  "BALKAN RADYATÖR SANAYİ VE TİC.LTD.ŞTİ./ ANTALYA": "Ali Osman Demir",
  "BALKAN RADYATÖR SANAYİ VE TİC.LTD.ŞTİ./ ATAŞEHİR": "Ali Osman Demir",
  "BALKAN RADYATÖR SANAYİ VE TİC.LTD.ŞTİ./ BURSA": "Ali Osman Demir",
  "BALKAN RADYATÖR SANAYİ VE TİC.LTD.ŞTİ./ İKİTELLİ": "Ali Osman Demir",
  "BALKAN RADYATÖR SANAYİ VE TİC.LTD.ŞTİ./ İZMİR": "Ali Osman Demir",
  "BALKAR OTO YEDEK PARÇA - SÜMEYYA BALCI": "Engin Alaca",
  "BALLI OTO ÇIKMA YEDEK PARÇALARI - ARİF ALTIN": "Mustafa Koçalı",
  "BALVAK GRUP OTOMOTİV GIDA SAN.VE TİC.LTD.ŞTİ.": "Eren Ateş",
  "BANDIRMA OTO IŞIK OTOM.YED.PAR.İNŞ.VE TUR.TİC.SAN.LTD.ŞTİ.": "Cüneyt Baş",
  "BAR-CAR DESIGN - BARIŞ PALAN": "Eren Aykut",
  "BARBARUS MOTORLU ARAÇLAR LTD.ŞTİ.": "Recep Yılmaz",
  "BARIŞ OTOMOTİV - MUSTAFA YAŞILAK": "Alpaslan Değer",
  "BARIŞ OTOMOTİV - İHSAN ÇELİK": "Ali Osman Demir",
  "BATMAN TİCARET - SİNAN BATMAN": "Serdar Parlakkan",
  "BAVYERA OTO YEDEK PARÇA - CENGİZ TOPÇU": "Alpaslan Değer",
  "BAY CC OTOMOTİV - CEMAL COŞKUN": "Mustafa Koçalı",
  "BAYINDIR OTO - VOLKAN BAYINDIR - ŞUBE": "Engin Alaca",
  "BAYINDIR OTOMOTİV - SÜLEYMAN BAYINDIR": "Onur Selvi",
  "BAYSAL YEDEK PARÇA OTO ELEKT.ELEKT.İNŞ.SAN.TİC.LTD.ŞTİ.": "Serdar Parlakkan",
  "BAYTUR MAKİNA OTOMOTİV SANAYİ VE TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "BAĞBARS OTO YEDEK PARÇA - SAMİ BAĞBARS": "Alpaslan Değer",
  "BAŞ-ER OTOMOTİV - İSMAİL OKUR": "Eren Ateş",
  "BAŞBUĞ OTOMOTİV YEDEK PARÇA - HASAN BAŞBUĞ": "Ferhan Demir",
  "BAŞKANLAR RULMAN - ONUR ATAMER VE MAHMUT AKARDERE ADİ ORT.": "Cüneyt Baş",
  "BAŞKENT BİLYA KEÇE OTOM.İNŞ.SAN.VE TİC.LTD.ŞTİ.": "Eren Ateş",
  "BAŞKENT VOLKSWAGEN MURAT KURT VE ORHAN ÜNAL ORT.": "Eren Ateş",
  "BAŞKENT YEDEK PARÇA - FIRAT CİHAN": "Eren Ateş",
  "BAŞTÜRK ANKARA OTO YEDEK PARÇA NAK TURZ.SAN.VE TIC.LTD.ŞTI.": "Seçkin Ozan Akıllı",
  "BAŞÇAR OTOMOTİV - MEHMET BAŞ": "Alpaslan Değer",
  "BBA GRUP RULMAN GÜÇ AKT.SİST.SAN.VE TİC.LTD.ŞTİ.": "Engin Alaca",
  "BEKAROĞLU OTOMOTİV - HALİT BEKAROĞLU": "Cüneyt Baş",
  "BEKMEZOĞLU OTOMOTİV - HÜSEYİN BEKMEZOĞLU": "Alpaslan Değer",
  "BEKİL OTOMOTİV YEDEK PARÇA TİCARETİ - OĞUZHAN BEKİL": "Engin Alaca",
  "BEKİR EKMEKÇİ OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "BEKİR KARA - İBRAHİM ATAK ORTAKLIĞI": "Erbay Atlı",
  "BEMSAN MOTORLU ARAÇLAR TİCARET VE SAN.LTD.ŞTİ. / ŞUBE": "Recep Yılmaz",
  "BENZER OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Ferhan Demir",
  "BENZLER OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Ferhan Demir",
  "BERAT OTOMOTİV OTO ALIM SATIM YEDEK PARÇA - MEHMET YEŞİLKURT": "Serdar Parlakkan",
  "BERATNUR OTOMOTİV İNŞAAT HİZ.TUR.PAZ.SAN.TİC.LTD.ŞTİ.": "Alpaslan Değer",
  "BERATSAN OTOMOTİV SANAYİ TİCARET LTD.ŞTİ.": "Cüneyt Baş",
  "BERK  OTOMOTİV - VEHBİ ÖZEL": "Serdar Parlakkan",
  "BERK OTO VOLKSWAGEN - BERK FAFAL": "Sefa Akkan",
  "BERK OTOMOTİV OPEL - AKIN ÇEVİRME": "Ferhan Demir",
  "BERK OTOMOTİV VOLKSWAGEN - AKIN ÇEVİRME": "Ferhan Demir",
  "BERK OTOMOTİV YED.PARÇ.VE DIŞ TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "BERKAY OTOMOTİV - MURTAZA AYDIN": "Ali Osman Demir",
  "BERRA OTO 2. EL-ORİJİNAL - YUNUS EMRE DEMİRBAZ": "Erbay Atlı",
  "BEYAZ GARAGE - METİN AZMAN": "Eren Aykut",
  "BEYLERBEYİ ORJİNAL YEDEK PARCALARI - HÜSEYİN BÖLÜK": "Seçkin Ozan Akıllı",
  "BEŞPARMAK SAN. VE TİC.LTD.ŞTİ.": "Seçkin Ozan Akıllı",
  "BEŞPARMAK SAN. VE TİC.LTD.ŞTİ./ ŞUBE": "Seçkin Ozan Akıllı",
  "BG GÜMÜŞOK OTO SANAYİ VE TİC.LTD.ŞTİ.": "Erbay Atlı",
  "BLACK OTOMOTİV - AYDIN EMRE ORTA": "Engin Alaca",
  "BM NİSSA GRUP İNŞAAT OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "BMN OTOMOTİV SAN.TİC.LTD.ŞTİ.": "Eren Ateş",
  "BMS ARAÇ YEDEK PARÇA SANAYİ VE TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "BODY GARAGE OTO AKSESUAR - CEVDET ÖZYILDIRIM": "Eren Aykut",
  "BONCUK OTO YEDEK PARÇA LTD.ŞTİ": "Recep Yılmaz",
  "BORA OTO YEDEK PARÇA LTD.ŞTİ.": "Ali Osman Demir",
  "BORA OTOMOTİV - BORA AKÇA": "Erbay Atlı",
  "BORAN OTOMOTİV TEK.SERVİS.TRZM GIDA TEKSTİL SAN. VE DIŞ TİC.LTD.ŞTİ./ KOCASİNAN": "Mustafa Koçalı",
  "BOZACI OTOMOTİV - EMRE BOZACI": "Ömer Kınalı",
  "BOZKAR YEDEK PARÇA OTOMOTİV SAN. VE TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "BOĞAZİÇİ GRUP MOTORLU TAŞITLAR A.Ş.": "Cüneyt Baş",
  "BOĞAZİÇİ MOTORLU ARAÇLAR TİCARET LTD.ŞTİ.": "Cüneyt Baş",
  "BRS OTOMOTİV - MUKADDES USBURAK": "Recep Yılmaz",
  "BSD PETROL OTOM.İNŞ.NAK.VE GIDA SAN.TİC.A.Ş. / ANKARA ŞUBE": "Cüneyt Baş",
  "BSD PETROL OTOM.İNŞ.NAK.VE GIDA SAN.TİC.A.Ş. / DİYARBAKIR ŞUBE": "Cüneyt Baş",
  "BSD PETROL OTOM.İNŞ.NAK.VE GIDA SAN.TİC.A.Ş. / İSTANBUL ŞUBE": "Cüneyt Baş",
  "BSN OTOMOTİV YED.PARÇ.SAN.TİC. - BÜŞRA DOĞDU": "Engin Alaca",
  "BUDAK OTOMOTİV YED.PARÇA - ADİL BUDAK": "Sefa Akkan",
  "BUDUN OTOMOTİV - METİN BUDUN": "Recep Yılmaz",
  "BURAK ACER": "Eren Ateş",
  "BURAK ERCAN BBD OTO": "Serdar Parlakkan",
  "BURAK OTO - ERSAN SARI": "Serdar Parlakkan",
  "BURAK OTO 06 OTOMOTİV İNŞ.İTH.İHR.VE TİC.LTD.ŞTİ.": "Eren Ateş",
  "BURAK OTOMOTİV - AZİZ TAYLAN": "Ferhan Demir",
  "BURCAN OTOMOTİV SAN.TİC. VE SERVİS HİZM.LTD.ŞTİ.": "Engin Alaca",
  "BURUŞOĞLU OTOMOTİV - KÖKSAL BURUŞ": "Engin Alaca",
  "BY AKILLI GARAGE - CENGİZHAN AKILLI": "Eren Aykut",
  "BY ÇUKUROVA OTOMOTİV VE YED.PAR.TİC.LTD.ŞTİ.": "Serdar Parlakkan",
  "BYM YEDEK OTO PARÇA - YUKSEL DURAN": "Alpaslan Değer",
  "BÜLENT OTO YEDEK PARÇA - BÜLENT ATEŞLİOĞLU": "Sefa Akkan",
  "BÜLENT YUKAY": "Ferhan Demir",
  "BÜLENT YUKAY 2": "Ferhan Demir",
  "BÜYÜK RADYATÖR - OKTAY BULAK": "Ali Osman Demir",
  "BÜYÜK ÇAMLICA OTOMOTİV YEDEK PARÇA TİC.LTD.ŞTİ.": "Sefa Akkan",
  "BÜYÜKKARACA TİC. - HASAN BÜYÜKGÜLER": "Erbay Atlı",
  "BİLBENLER OTOMOTİV İNŞAAT NAK.YED.PAR.İTH.İHR.SAN.VE TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "BİLDİK OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Serdar Parlakkan",
  "BİLGİ YEDEK PARÇA OTOMOTİV SAN.TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "BİLGİN TİCARET -  FAİK BİLGİN": "Engin Alaca",
  "BİLGİNER OTOMOTİV SAN. VE TİC.LTD.ŞTİ.": "Erbay Atlı",
  "BİLİR OTO VE YEDEK PARÇA OPEL ÖZEL SERVİSİ - MEMATİ BİLİR": "Serdar Parlakkan",
  "BİMAŞ OTO RADYATÖR NAK.TUR.TEKS.HAY.İNŞ.GID.İTH.İHR.SAN.VE TİC.LTD.ŞTİ.": "Ali Osman Demir",
  "BİMPAR OTOMOTİV YEDEK PARÇA SAN.TİC.LTD.ŞTİ.": "Erbay Atlı",
  "BİPAR OTOMOTİV YEDEK PARÇA - ERTUĞRUL KOÇAK": "Erbay Atlı",
  "BİR-PAR YEDEK PARÇA PAZ.TURZ. SAN.TİC.LTD.ŞTİ.": "Ali Osman Demir",
  "BİRBİRİ TİCARET ORJİNAL YEDEK PARÇALARI - SUAT BİRBİRİ": "Serdar Parlakkan",
  "BİRCAN OTOMOTİV - ÇAĞAN BİRCAN": "Serdar Parlakkan",
  "BİRTAŞ OTO -  MEHMET BİRTAŞ": "Ferhan Demir",
  "BİSRA OTOMOTİV -  ÖZER ALTUNTAŞ": "Engin Alaca",
  "BİZİM OTOMOTİV - DİLEK ZORBACI": "Recep Yılmaz",
  "BİZİM PARÇA OTOMOTİV TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "BİÇERLER OTOMOTİV PET.İNŞ. SAN.VE TİC.LTD.ŞTİ.": "Eren Ateş",
  "CABU OTOMOTİV MAKİNA SAN.VE TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "CAN CAN OPEL & CHEVROLET BİROL KARASU": "Recep Yılmaz",
  "CAN KARDEŞLER OTOMOTİV SAN. VE TİC. LTD. ŞTİ": "Eren Ateş",
  "CAN KARDEŞLER RADYATÖR TEK.HAY.OTOM.YED.PAR.MAK.İNŞ.TUR.SAN. VE TİC.LTD.ŞTİ.": "Ali Osman Demir",
  "CAN OTOMOTİV YEDEK PARÇA - CAN FAFAL": "Sefa Akkan",
  "CAN RADYATÖR - AYŞEGÜL CAN": "Serdar Parlakkan",
  "CAN TUNING - CEMİL TUNÇAY": "Cüneyt Baş",
  "CAN TUNİNG - CEMAL TUNÇAY": "Cüneyt Baş",
  "CAN-SER OTOMOTİV SERV.YED.PAR.GID.TUR.SAN.VE TİC.LTD.ŞTİ.": "Sefa Akkan",
  "CANDAN OTOMOTİV TEKSTİL GIDA SAN.VE TİC.LTD.ŞTİ.": "Erbay Atlı",
  "CANLAR OTO TAMİR - MASUM USTA": "Alpaslan Değer",
  "CANMER GRUP OTOMOTİV İNŞ.HURD.İTH.İHR.SAN.VE TİC.LTD.ŞTİ.": "Seçkin Ozan Akıllı",
  "CANSUN OTOMOTİV SANAYİ VE DIŞ TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "CANTAŞ AUTO - İSMAİL TAŞKIN": "Sefa Akkan",
  "CAR PARTS TR OTOMOTİV VE YEDEK PARÇA SANAYİ TİCARET A.Ş.": "Cüneyt Baş",
  "CEMAL OPEL YEDEK PARCA- CEMAL ŞENGÜL": "Sefa Akkan",
  "CEMALİ OTO - NURETTİN MAŞALI": "Engin Alaca",
  "CEREN OTOMOTİV-MURAT ÖZBÖLÜK": "Mustafa Koçalı",
  "CES AUTO PERTS - CEM SARI": "Eren Aykut",
  "CETU OTOMOTİV LTD.ŞTİ.": "Recep Yılmaz",
  "CEYHAN OTOMOTİV KENAN CEYHAN": "Ferhan Demir",
  "CEYHAN YEDEK PARÇA OTOMOTİV NAK.EML.İTH.İHR.SAN.VE TİC.LTD.ŞTİ.": "Serdar Parlakkan",
  "CEYLAN BİLYA - YASİN ŞEKER": "Alpaslan Değer",
  "CEYLAN OTOMOTİV - CEMİL CEYLAN": "Mustafa Koçalı",
  "CEYPAR OTO - KEMAL CEYHAN / İKİTELLİ": "Mustafa Koçalı",
  "CINCIK OTOMOTİV ORJİNAL OTO YEDEK PARÇA - EROL ÖZUFACIK": "Alpaslan Değer",
  "CLASS MERCEDES YEDEK PARÇA BAKIM VE ONARIM MERKEZİ - FİKRET ERDEM": "Recep Yılmaz",
  "CLB KARDEŞLER OTOMOTİV İNŞ.TEM.TEKS.PET.İHR.İTH.SAN.VE TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "CME TİCARET - KEREM EROĞUL": "Recep Yılmaz",
  "CNG OTOMOTİV USD (İHRACAT)": "Cüneyt Baş",
  "CNG TUNING - MURAT CAN": "Eren Aykut",
  "CNG TUNİNG - MURAT CAN": "Eren Aykut",
  "CNR OTOMOTİV YEDEK PARÇA - CANER GÖLBAŞI": "Ferhan Demir",
  "CS OTOMOTİV DIŞ TİCARET LTD.ŞTİ.": "Recep Yılmaz",
  "CÜNEYT OTO YEDEK PARÇA - CÜNEYT KILIÇASLAN": "Alpaslan Değer",
  "CİHAN OTO SAN.VE TİC.LTD.ŞTİ.": "Ferhan Demir",
  "DAS GARAGE OTOMOTİV VE TİC.LTD.ŞTİ.": "Serdar Parlakkan",
  "DAVUT OTOMOTİV - DAVUT TEKİNALP": "Alpaslan Değer",
  "DAYEN OTOMOTİV OTO YEDEK PARÇA İTH.İHR.SAN.LTD.ŞTİ": "Sefa Akkan",
  "DEDELER OTOMOTİV - MUSA DEDELER": "Engin Alaca",
  "DEKOR OTOMOTİV - EYÜP ÇOTUL": "Recep Yılmaz",
  "DEMİR YEDEK PARÇA OTOMOTİV TURZ.NAKL.İTH.İHR.TİC.VE SAN.LTD.ŞTİ.": "Serdar Parlakkan",
  "DEMİR YEDEK PARÇA OTOMOTİV TURZ.NAKL.İTH.İHR.TİC.VE SAN.LTD.ŞTİ./ ŞUBE": "Serdar Parlakkan",
  "DEMİRBAZ OTO YEDEK PARÇA - OĞUZHAN DEMİRBAZ": "Erbay Atlı",
  "DEMİRKAN OTO YEDEK PARÇA - FARUK DEMİRKAN": "Ömer Kınalı",
  "DEMİRKAN OTO YEDEK PARÇA İTHALAT VE İHR.LTD.ŞTİ.": "Ömer Kınalı",
  "DENEME ZEUS/İSTANBUL": "Cüneyt Baş",
  "DENLİ YEDEK PARÇA - AHMET DENLİ": "Alpaslan Değer",
  "DENİZ OTOMOTİV - ÖZGE ÇAĞRI ERGİN": "Recep Yılmaz",
  "DENİZ OTOMOTİV - ÖZGE ÇAĞRI ERGİN / 2": "Recep Yılmaz",
  "DENİZ OTOMOTİV OTO YEDEK PARÇA TOPTAN VE PERAKENDE - REGAYİP DENİZ": "Ömer Kınalı",
  "DENİZ ÖZEL WOLKSWAGEN GROUP SERVİCE MEHMET MİRİOĞLU VE ORT.": "Mustafa Koçalı",
  "DEPAR OTOMOTİV - AHMET DEMİRCİ": "Ömer Kınalı",
  "DEPO OTOMOTİV SANAYİ VE TİC.LTD.ŞTİ.": "Sefa Akkan",
  "DERVİŞOĞULLARI OTO ÇIKMACI YEDEK PARÇA ALIM SATIMI - VEDAT TETİK": "Recep Yılmaz",
  "DEĞER OTO YEDEK PARÇA EREN ÇELİK HASAN BALTACI ADİ ORTAKLIĞI": "Recep Yılmaz",
  "DEĞİRMENCİ OTO YED.PAR. - AYŞE DEĞİRMENCİ": "Engin Alaca",
  "DGK OTOMOTİV YEDEK PARÇA TİC.İTH.VE İHR.LTD.ŞTİ.": "Mustafa Koçalı",
  "DGN OTOMOTİV YEDEK PARÇA - ERCAN DOĞAN": "Sefa Akkan",
  "DIAMOND CAR OTOMOTİV - AKIN ÖZTÜRK": "Recep Yılmaz",
  "DKMC GROUP OTOMOTIV YEDEK PARÇA - SERKAN DÖKMECI": "Recep Yılmaz",
  "DME OTOMOTİV İNŞAAT MAD.ORM.ÜR.SAN.VE TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "DMR GARAGE OTO AKSESUAR - ALİ USLUER": "Eren Aykut",
  "DNZ OTOMOTİV YED.PAR.VE SER.HİZM. - MUSTAFA DENİZ": "Ferhan Demir",
  "DONAT OTOMOTİV GIDA VE MOBİLYA SAN.TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "DORUK AUTO YEDEK PARÇA SANAYİ VE TİCARET A.Ş": "Engin Alaca",
  "DORUK OTO YEDEK PARÇA - SAKİNE SAVA": "Engin Alaca",
  "DORUK OTOMOTİV İNŞ.TUR.TİC.LTD.ŞTİ": "Onur Selvi",
  "DORUK YEDEK PARÇA / REINZ TL": "Cüneyt Baş",
  "DORUK YEDEK PARÇA / USD": "Cüneyt Baş",
  "DORUK YEDEK PARÇA OTO.İNŞ.TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "DOST OTO - MUHAMMET BAHİTTİN BOZKURT": "Serdar Parlakkan",
  "DOSTLAR KAPORTA - MAHMUT YAŞAR": "Onur Selvi",
  "DOĞAN OPEL CHEVROLET YEDEK PARCA - DOĞAN DEMİRAL": "Sefa Akkan",
  "DOĞAN OTO YEDEK PARÇA - DOĞAN TERMİ": "Onur Selvi",
  "DOĞAN OTO YEDEK PARÇA - ŞERAFETTİN NAZLIGÜL": "Seçkin Ozan Akıllı",
  "DOĞAN OTOMOTİV - ABDULLAH DOĞAN": "Seçkin Ozan Akıllı",
  "DOĞAN OTOMOTİV SAN. VE TİC. LTD.ŞTİ.": "Ferhan Demir",
  "DOĞANLAR OTOMOTİV-CEMAL DOĞAN": "Alpaslan Değer",
  "DOĞRU VOLMER OTOM. - HÜSEYİN ONUR DOĞRU": "Onur Selvi",
  "DOĞUŞ OTO PARÇALARI A.Ş.": "Eren Ateş",
  "DOĞUŞ OTO RADYATÖR - MÜKAYİL TAVLIBIYIK": "Ali Osman Demir",
  "DS OTOMOTİV İNŞAAT PETROL TUR.GID.TEK.SAN.VE TİC LTD.ŞTİ.": "Eren Ateş",
  "DURU OTOMOTİV - FATİH ŞAHİN": "Mustafa Koçalı",
  "DUVAKLI OTO - ELİF DUVAKLI": "Mustafa Koçalı",
  "DÖRTEL OTOMOTİV SAN.PAZ.TİC.LTD.ŞTİ": "Ferhan Demir",
  "DÜNDAR OTO YEDEK PARÇA - MUHAMMED DÜNDAR": "Alpaslan Değer",
  "DÜNYA OTOMOTİV YEDEK PARÇA OTO CAM VE AKSESUR - HAMİT KAYA": "Cüneyt Baş",
  "DÜZGÜN OTOMOTİV VE YEDEK PARCA - MUHARREM DÜZGÜN": "Ömer Kınalı",
  "DİAMON GROUP OTOMOTİV TİCARET LTD.ŞTİ.": "Ferhan Demir",
  "DİKSAN OTO YEDEK PARÇA PAZARLAMA SAN.TİC.LTD.ŞTİ.": "Sefa Akkan",
  "DİLEK YERLİKAYA": "Recep Yılmaz",
  "DİPAR OTOMOTIV ALMAN JAPON YED.PAR. - MUSTAFA ELEZ": "Alpaslan Değer",
  "DİRİK OTOMOTİV SANAYİ VE TİC.LTD.ŞTİ.": "Sefa Akkan",
  "EBRU UĞUR YILDIRIM": "Mustafa Koçalı",
  "EBUBEKİR SIDDIK BAYAZİT": "Recep Yılmaz",
  "EF GARAGE - EMİR ŞENTÜRK": "Eren Aykut",
  "EFE OTOMOTİV - HÜSEYİN EFE BOLLU": "Sefa Akkan",
  "EFE OTOMOTİV - HÜSNÜ TANER KARA": "Ferhan Demir",
  "EFE VOLKSWAGEN OTO YEDEK PARÇA - EMRAH ŞAHİN": "Eren Ateş",
  "EFELER OTO YED.PAR. - HASAN ÜLKER- FEHMİ GÖKBAYRAK ADİ ORT.": "Sefa Akkan",
  "EFON OTO AKSESUAR - MEHMET ONUR DEMİR": "Eren Aykut",
  "EFORS YEDEK PARÇA OTOMOTİV İNŞ.SAN.TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "EFR TECH & AUTOMOTİVE - UMUT EFE KOCAASLAN": "Ferhan Demir",
  "EGE OTO YED.PARÇA VE AKS. - LEVENT TUNÇKOL": "Engin Alaca",
  "EGE RULMAN - FERDAN AKAR": "Cüneyt Baş",
  "EGEDENPAR OTOMOTİV TİC. LTD. ŞTİ./ ŞUBE": "Engin Alaca",
  "EGEDENPAR OTOMOTİV TİC. LTD. ŞTİ./ ŞUBE 2": "Engin Alaca",
  "EGEDENPAR OTOMOTİV TİC.LTD.ŞTİ.": "Ferhan Demir",
  "EGEVOS OTOMOTİV YEDEK PARÇA - LEYLA KALPAKÇIOĞLU": "Sefa Akkan",
  "EGÜVEN OTO YEDEK PARCA MAD.TUR.INS NAK.GIDA TAR.HAY.PAZ.IMAL.ITH.IHR.SAN VE TIC.LTD STI": "Ömer Kınalı",
  "EK - ENES KAÇAR": "Engin Alaca",
  "EKC GARAGE - MEHMET CAN EKİCİ": "Onur Selvi",
  "EKLER OTOMOTİV YEDEK PARÇA VE İNŞ.SAN.TİC.LTD.ŞTİ.": "Ferhan Demir",
  "EKO OTO RADYATÖR SAN.VE TİC.LTD.ŞTİ": "Ali Osman Demir",
  "EKO YEDEK PARÇA VE OTOMOTİV A.Ş.": "Recep Yılmaz",
  "EKSEN OTOMOTİV VOLKSWAGEN OTO ELEKTRİK YEDEK PARÇA - MURAT BAKKAL": "Onur Selvi",
  "EKİMPAR DIŞ TİCARET LTD. ŞTİ.": "Cüneyt Baş",
  "EKİN OTOMOTİV - EKİN KANBUR": "Mustafa Koçalı",
  "EL-SAN OTOMOTİV SAN. VE TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "ELDA OTOMOTİV YED.PAR. - ÖMER FARUK YURTTÜRK": "Mustafa Koçalı",
  "ELVER OTOMOTİV-FATİH CANSESLİ": "Sefa Akkan",
  "ELİBÜYÜK OTOMOTİV TİC.VE SAN.LTD.ŞTİ.": "Ferhan Demir",
  "ELİTE AUTO OTOMOTİV İNŞ.PET.ÜRÜNLERİ SAN.TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "EMAYSAN OTOMOTİV YEDEK PARÇA SAN.TİC.LTD.ŞTİ.": "Ali Osman Demir",
  "EMB YAZILIM VE OTOMOTİV SAN. TİC. LTD. ŞTİ.": "Mustafa Koçalı",
  "EMC GARAGE - ERDOĞAN CÖDEL": "Eren Aykut",
  "EMR ULAŞ OTOMOTİV TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "EMRAH OTO YEDEK PARÇA - EMRAH ERDEM": "Eren Ateş",
  "EMRE ERKAN ÇELEBİ": "Recep Yılmaz",
  "EMRE OPEL - EMRE KARATEPE": "Sefa Akkan",
  "EMRE OTOMOTİV -  MEHMET ÖNDER": "Ömer Kınalı",
  "EMRE YEDEK PARÇA - EMRE ALTINTOP": "Erbay Atlı",
  "EMİN OTOMOTİV YED.PAR. - MEHMET EMİN ŞAHAN": "Alpaslan Değer",
  "EMİN ÖZEL ÖZELLER OTO YEDEK PARÇA SAN.VE TİC.LTD.ŞTİ.": "Serdar Parlakkan",
  "EMİR OTO YEDEK PARÇA - ERDİNÇ BURAK ARSLAN": "Sefa Akkan",
  "EN-KA OTOMOTİV - ALİ BAYRAM MARANGOZ": "Alpaslan Değer",
  "ENDERİN OTOMOTİV SANAYİ İTHALAT İHR.LTD.ŞTİ.": "Eren Ateş",
  "ENES GÖZEN": "Mustafa Koçalı",
  "ENES OTO RADYATÖR  - İBRAHİM ÇERİKCİ": "Ali Osman Demir",
  "ENES OTO RADYATÖR - İBRAHİM ÇERİKCİ / 2": "Ali Osman Demir",
  "ENES OTOMOBIL SISTEMLERI SAN VE TIC LTD ŞTI": "Mustafa Koçalı",
  "ENGİN OTO - ENGİN KARABAŞ": "Mustafa Koçalı",
  "ENGİN OTOMOTİV - ENGİN GÖZTAŞI": "Ferhan Demir",
  "ENGİN OTOMOTİV ELK. ELEKTRO. İNŞ. SAN. VE TİC. LTD. ŞTİ.": "Ferhan Demir",
  "ENKAR OTOMOTİV - ENGİN ÖZCAN": "Recep Yılmaz",
  "ENKAY GRUP OTOMOTİV SAN.VE TİC. A.Ş.": "Ferhan Demir",
  "ENKOLAY PARÇA - MEHMET CEYLAN": "Mustafa Koçalı",
  "ENİS BAŞ TL / SATIŞ": "Cüneyt Baş",
  "ENİS BAŞ USD / TOPTAN": "Cüneyt Baş",
  "ERAY IŞITAN - IŞITAN GARAGE": "Eren Aykut",
  "ERBAL OTOMOTİV İNŞAAT TEKSTİL SANAYİ VE TİCARET LİMİTED ŞİRKETİ": "Mustafa Koçalı",
  "ERCAN 1 OTOMOTİV İNŞAAT TUR.İTH.İHR.SAN.VE TİC.LTD.ŞTİ.": "Alpaslan Değer",
  "ERCAR OTO YEDEK PARÇA - ERAY BOZKURT": "Ferhan Demir",
  "ERD GARAJ - ERDEM SEVİNÇ": "Eren Aykut",
  "ERDEM KARDEŞLER - SAMED ERDEM": "Ferhan Demir",
  "ERDEM OPEL - ERDEM ŞEHAN": "Sefa Akkan",
  "ERDEM OPEL - ERDEM ŞEHAN / ŞUBE": "Cüneyt Baş",
  "ERDEM OTO YEDEK PARÇA - SEVİM ERDEM": "Mustafa Koçalı",
  "ERDEM TİCARET - İRFAN ERDEM": "Engin Alaca",
  "ERDEMOĞLU MOTORLU ARAÇLAR VE YEDEK PARÇALARI SAN. VE TİC.LTD.ŞTİ.": "Alpaslan Değer",
  "ERGAZİ OTOMOTİV - EMRE ERAY ÖZBEK": "Eren Ateş",
  "ERGÜN OTOMOTİV - HAKAN ERGÜN": "Erbay Atlı",
  "ERHAN OTOMOTİV - ABDULLAH KARCAN": "Mustafa Koçalı",
  "ERKARA OTOMOTİV TİC.VE SAN A.Ş.": "Engin Alaca",
  "ERKO DYNAMICS SAVUNMA TEKNOLOJİ SANAYİ VE TİCARET A.Ş.": "Recep Yılmaz",
  "ERKO OTOMOTİV SANAYİ İÇ VE DIŞ TİC. A.Ş.": "Cüneyt Baş",
  "ERKOL TİC. YEDEK PARÇA AKS. TOPTAN VE PERAKENDE - MEHMET PULAT": "Alpaslan Değer",
  "ERLER OTOMOTİV SERVİS HİZMETLERİ TİC.VE SAN.LTD.ŞTİ./ ŞUBE": "Ferhan Demir",
  "EROĞLU OTOMOTİV - HALİM EROĞLU": "Sefa Akkan",
  "ERPAR OTOMOTİV - ERKAN AKZİRVE": "Mustafa Koçalı",
  "ERSOY KAN OTOMOTİV İTH.İHR.SAN.VE TİC.LTD.ŞTİ.": "Onur Okumuş",
  "ERTAN OTO - FAHRETTİN DÜZ": "Engin Alaca",
  "ERTAŞ OTO YEDEK PARÇA - SALİH ERTAŞ": "Cüneyt Baş",
  "ERTAŞ OTOMOTİV OTO YEDEK PARÇA SAN.TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "ERTENOĞULLARI OTOMOTİV İNŞ.TUR.SAN.VE TİC.LTD.ŞTİ.": "Alpaslan Değer",
  "ERTÜRK MOTORLU ARAÇLAR İTHALAT VE TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "ERVA OTO YEDEK PARÇA - MURAT ERGUVAN": "Ferhan Demir",
  "ERYA OTO YEDEK PARÇ. OTOMOTİV DIŞ TİC. SAN. VE TİC. LTD. ŞTİ.": "Alpaslan Değer",
  "ERÇELOĞLU TİCARET ORJİNAL YEDEK PARÇA-GÖKHAN ERÇEL": "Serdar Parlakkan",
  "ES DEMİR OTO YEDEK PARÇA OTOMOTİV SAN. VE TİC.LTD.ŞTİ.": "Engin Alaca",
  "ES GÜNAY OTOMOTİV GIDA İNŞ. İTH. İHR. SAN. TİC. LTD. ŞTİ.": "Eren Ateş",
  "ES OTO YEDEK PARÇA - SELAHATTİN SERBEST": "Ferhan Demir",
  "ES OTOMOTİV - ERGÜN BOZ": "Recep Yılmaz",
  "ES OTOMOTİV SANAYİ VE TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "ESEN FORD - FERHAT ESEN": "Eren Ateş",
  "ESENPA OTO YEDEK PARCA TAM.SERVIS HIZM. SAN. VE TIC. LTD STI": "Sefa Akkan",
  "ESKİŞEHİR VOLKWAGEN YEDEK PARÇA - FATİH TÜYSÜZ": "Engin Alaca",
  "ESNAF OTOMOTİV - MELTEM TOPÇU": "Mustafa Koçalı",
  "ESPAR TURİZM OTOM.EML.İNŞ.GIDA GİY.TAR.TEM.TEKS.TAŞ.İTH.İHR.SAN.VE TİC.LTD.ŞTİ.": "Onur Selvi",
  "ESİN OTO RADYATÖR VE YEDEK PARÇA - HALİL ESİN": "Ali Osman Demir",
  "EVO YEDEK PARÇA OTOMOTİV TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "EYLÜL OTO YEDEK PARÇA - NİGAR KARABIÇAK": "Recep Yılmaz",
  "EYLÜL RADYATÖR OTO YEDEK PARÇA SANAYİ VE TİC.LTD.ŞTİ.": "Ali Osman Demir",
  "EZEL OTOMOTİV - ZARİF ÇARDAK": "Erbay Atlı",
  "EZER OTO YEDEK PARÇA VE SAN.TİC.LTD.ŞTİ.": "Serdar Parlakkan",
  "EZER OTO YEDEK PARÇA ZEKERİYA EZER": "Serdar Parlakkan",
  "EŞDAĞ OTOMOTİV TURZ.SAN.VE TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "EŞREFOĞLU OTOMOTİV SANAYİİ VE TİC.LTD.ŞTİ.": "Ferhan Demir",
  "EŞREFOĞLU TİCARET - RIFAT ÇELİK": "Ömer Kınalı",
  "FARBEN OTOMOTİV SANAYİ TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "FARCI ÖMER - ÖMER KARAMAN": "Engin Alaca",
  "FARK OTO YEDEK PARÇA - SABRİ ALİ FARUK KOTANOĞLU": "Engin Alaca",
  "FATİH ALİ İMREN OTOM.İNŞ.TUR.SAN.VE TİC.LTD.ŞTİ.": "Eren Ateş",
  "FATİH GÖKER OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Erbay Atlı",
  "FATİH OTO EGZOS VE RADYATÖR SERVİSİ - FATİH GİRİŞ": "Ali Osman Demir",
  "FATİH OTO ORJ.VE ÇIKMA YEDEK PARÇA - EMRAH DURAN": "Recep Yılmaz",
  "FATİH OTO YEDEK PARÇA SANAYİ TİC.LTD.ŞTİ.": "Sefa Akkan",
  "FATİH OTOMOTİV - CANSU KARAMUK": "Seçkin Ozan Akıllı",
  "FATİH OTOMOTİV - FATİH YALÇIN": "Sefa Akkan",
  "FAVE OTOMOTİV - HACI KÖSE": "Ömer Kınalı",
  "FCS MOTORLU ARAÇLAR SANAYİ VE TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "FERDA OTO AKSARAY": "Ferhan Demir",
  "FERMAS OTOMOTİV YEDEK PARÇA DAĞITIM ANONİM ŞİRKETİ": "Cüneyt Baş",
  "FERMET OTO YEDEK PARÇA - MERT YÜKSEL": "Sefa Akkan",
  "FIRAT OTOMOTİV - ERSİN FIRAT": "Mustafa Koçalı",
  "FIRAT1 OTOMOTİV YED.PAR.PET.ÜR.LOJ.İNŞ.TUR.GID.TAR.HAY.EM.İTH.İHR.VE SAN.LTD.ŞTİ.": "Alpaslan Değer",
  "FK TUNİNG SHOP - ERSİN KUMAŞCI": "Engin Alaca",
  "FLAPWORKS GARAGE - EMRE YILDIRIM": "Ferhan Demir",
  "FLEET ASSİST OTOMOTİV VE YAZILIM LTD.ŞTİ.": "Recep Yılmaz",
  "FM DEMİRKAN OTOMOTİV KUY.GIDA TİC.LTD.ŞTİ.": "Eren Ateş",
  "FMZ OTO YEDEK PARÇA SAN.TİC. LTD. ŞTİ.": "Engin Alaca",
  "FORMÜL OTOMOTİV VE YEDEK PARÇA SAN.TİC.LTD.ŞTİ.": "Ferhan Demir",
  "FORS YED. PARÇ. VE OTOM. SAN. TİC. LTD. ŞTİ.": "Cüneyt Baş",
  "FRG FAR DÜNYASI - FIRAT GECE": "Serdar Parlakkan",
  "FİBERSAN TUNİNG DİZAYN OTOMOTİV SANAYİ TİC.LTD.ŞTİ.": "Eren Ateş",
  "FİMA OTOMOTİV - DURMUŞ YIKAR": "Serdar Parlakkan",
  "G25 GROUP SANAL MAĞAZACILIK TİCARET A.Ş.": "Cüneyt Baş",
  "GAMA OTO YEDEK PARÇA İTHALAT İHRACAT SANAYİ VE TİC.LTD.ŞTİ.": "Sefa Akkan",
  "GARAGE TUNİNG - ERTUNÇ KARAÇAR": "Eren Aykut",
  "GARAGE İSTANBUL İNŞAAT OTOM.SAN.VE TİC.LTD.ŞTİ.": "Onur Selvi",
  "GAZİ OTOMOTİV - UĞUR İBİLİ": "Alpaslan Değer",
  "GAZİANTEP KARDEŞLER BAKIM OTOM.HİZM.SAN.TİC.LTD.ŞTİ.": "Alpaslan Değer",
  "GAZİOĞLU DIŞ TİC. LTD. ŞTİ": "Ferhan Demir",
  "GAZİSAN OTOMOTİV İTH.İHR.SAN.TİC.LTD.ŞTİ": "Alpaslan Değer",
  "GE TEKNOLOJİ A.Ş.": "Ferhan Demir",
  "GEBZE BEKŞAN OTOMOTİV SAN.TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "GELİŞİM OTO YEDEK PARÇA - SEDAT SULAR": "Alpaslan Değer",
  "GEMPAR OTO YEDEK PARÇA - GÜRBÜZ ELMACIOĞLU": "Eren Ateş",
  "GENAL OTOMOTİV SANAYİ TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "GENEL OTO TİC.VE SAN.A.Ş.": "Cüneyt Baş",
  "GENÇ AKINCILAR İNŞ.TAAH.TUR.OTO.MAD.İTH.İHR.SAN.VE TİC.LTD.ŞTİ.": "Eren Ateş",
  "GENÇ TOKEL OTOMOTİV SANAYİ VE TİCARET LİMİTED ŞİRKETİ": "Mustafa Koçalı",
  "GESPAR MOTORLU ARAÇLAR OTOMOTIV SAN. VE TIC. LTD. ŞTİ.": "Onur Selvi",
  "GEZ YEDEK PARÇA VE OTOMOTİV SAN.TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "GLOBAL OTOMOBİL PARÇA İTHALAT İHRACAT SAN.VE TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "GRAND - PAR OTO YEDEK PARÇA - SERHAT DALBUDAK": "Alpaslan Değer",
  "GRM GİRMAN OTOMOTİV SANAYİ VE DIŞ TİC. LTD.ŞTİ.": "Erbay Atlı",
  "GRUP VOLKSWAGEN OTO YEDEK PARCALARI -  MEHMET EMİN KILIÇ": "Eren Ateş",
  "GÖKAR MUHENDİSLİK SAN VE TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "GÖKBEN RADYATÖR - SERDAR BARAN": "Ali Osman Demir",
  "GÖKŞEN OTOMOTİV YEDEK PARÇA - NERMİN ŞEN": "Ferhan Demir",
  "GÖLBAŞI YILDIZLAR OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "GÖZDE OTOMOTİV - ÖZGÜR KARAKAYA": "Ömer Kınalı",
  "GÖZETEN OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Onur Selvi",
  "GÖZTEPE OTOMOTİV - ORHAN GÖZTEPE": "Eren Ateş",
  "GÜLER OPEL - RECEP GÜLER": "Sefa Akkan",
  "GÜLER OTO OTO YED.PAR. - KERİM GÜLER": "Onur Selvi",
  "GÜLTEKİN OTOMOTİV - VEDAT GÜLTEKİN": "Alpaslan Değer",
  "GÜLÜM GÜL KAR OTO YEDEK PARÇA - VADET GÜLÜM": "Serdar Parlakkan",
  "GÜMÜŞKALE İÇ VE DIŞ TİCARET LTD.ŞTİ.": "Cüneyt Baş",
  "GÜNDEM OTO YED.PAR. - ÜMMÜYE DURGAÇ": "Ferhan Demir",
  "GÜNDÜZ OTOMOTİV OTO YEDEK PARÇALARI - ALİ GÜNDÜZ": "Ferhan Demir",
  "GÜNER GRUP OTOMOTİV SANAYİ TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "GÜNER OTO - ALİ GÜNER": "Erbay Atlı",
  "GÜNERLER OTOMOTİV VE İNŞ.SAN.TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "GÜNEY RADYATÖR KAL.KLİMA İNTER.TOP.PAR.SAT.VE TAMİR - YÜKSEL GÜNEY": "Ali Osman Demir",
  "GÜNEYDOĞU TİCARET OTO YEDEK PARÇA - AHMET DEMİRDAĞ": "Alpaslan Değer",
  "GÜNEŞ OTOMOTİV - AHMET GÜNEŞ": "Engin Alaca",
  "GÜNEŞ OTOMOTİV - TURHAN GÜNEŞ / SAKARYA": "Engin Alaca",
  "GÜNGÖR OTOMOTİV İTHALAT İHRACAT SAN.VE TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "GÜR OTOMOTİV - HASAN GÜRKAN": "Eren Ateş",
  "GÜRBÜZ KARDEŞLER OTO ALIM SATIM KOMISYON İŞLERİ - BEKİR GÜRBÜZ": "Eren Ateş",
  "GÜRBÜZ TİCARET OTO YEDEK PARÇA - OSMAN GÜRBÜZ": "Serdar Parlakkan",
  "GÜRLEYEN MOTORLU ARAÇ.VE OTO YED.PAR.SAN.TİC.LTD.ŞTİ.": "Ferhan Demir",
  "GÜRŞAH OTOMOTİV İNŞ.GIDA NAKLİYAT SAN.VE TİC.LTD.ŞTİ.": "Engin Alaca",
  "GÜVEN AUTO - FARUK GÜVEN": "Eren Ateş",
  "GÜVEN FAR OTO YEDEK PARÇA İTH. İHR. OTOMOTİV İNŞAAT TİC. LTD. ŞTİ.": "Eren Ateş",
  "GÜVEN OTO SALİHE GÜVEN ve ORTAĞI": "Eren Ateş",
  "GÜVEN OTO YEDEK PARÇA - İBRAHİM GÜVEN": "Alpaslan Değer",
  "GÜVEN OTOMOTİV - MAHSAR GÜVEN": "Eren Ateş",
  "GÜVEN OTOMOTİV - ZEKERİYE ÇELİK": "Serdar Parlakkan",
  "GÜVEN VOLKSWAGEN - MUSTAFA HAYRİ ARIKAN": "Eren Ateş",
  "GÜVEN VOLKSWAGEN - NURULLAH AYDIN": "Eren Ateş",
  "GÜZEL PREMİUM OTOMOTİV SAN.VE LTD.ŞTİ.": "Alpaslan Değer",
  "GÜZELLER OTOMOTİV YEDEK PARÇA - MURAT GÜZEL": "Alpaslan Değer",
  "GÜÇLÜ VOLKSWAGEN OTOM.İNŞ.PETR.GID.SAN.VE TİC.LTD.ŞTİ.": "Alpaslan Değer",
  "GİZ AUTO SPARE PARTS OTOMOTİV PAZ.A.Ş": "Cüneyt Baş",
  "GİZ YEDEK PARÇA VE OTOMOTİV DİŞ TİC.LTD.ŞTİ.": "Ferhan Demir",
  "HACIOĞULLARI OTOMOTİV - UĞUR ÖZTÜRK / ALMAN ŞUBE": "Mustafa Koçalı",
  "HAK KAPORTA OTO YEDEK PARÇA TİC.LTD.ŞTİ.": "Serdar Parlakkan",
  "HAMZA OTO RADYATOR - HAMZA BOĞACI": "Ali Osman Demir",
  "HAN OTOMOTİV YEDEK PARÇA SERVİS HİZMETLERİ - ERHAN ARIKAN": "Sefa Akkan",
  "HAN TEKNİK VOLKSW.AUDİ ÖZ.SER. - ORHAN KÖKSAL": "Ömer Kınalı",
  "HAN YEDEK PARÇA A.Ş.": "Recep Yılmaz",
  "HAS RULMAN OTOMOTİV SANAYİ VE TİCARET / TL": "Cüneyt Baş",
  "HAS RULMAN OTOMOTİV SANAYİ VE TİCARET / USD": "Cüneyt Baş",
  "HAS RULMAN OTOMOTİV SANAYİ VE TİCARET- HASAN KARATAŞ": "Cüneyt Baş",
  "HAS YEDEK PARÇA - ABDULLAH EVLİ": "Eren Ateş",
  "HAS ÖZCANLAR TARIM MAK. VE OTOM. TİC. LTD.ŞTİ": "Ömer Kınalı",
  "HASFORD OTOMOTİV YEDEK PARÇA SAN.VE TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "HASKAN OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Engin Alaca",
  "HASKÜRTÜNCÜ MOTORLU ARAÇLAR OTO.YED.PAR.SAN.TİC.LTD.ŞTİ.": "Seçkin Ozan Akıllı",
  "HAZARBEY TURİZM OTOMOTİV VE TAŞIMACILIK HİZMETLERİ TİC. LTD.ŞTİ.": "Cüneyt Baş",
  "HDS OTO SERVİS HİZMETLERİ TAŞ.TUR.İNŞ.TİC.LTD.ŞTİ.": "Onur Selvi",
  "HEDEF OTOMOTİV - HIDIR BARIŞ GELPİŞ": "Alpaslan Değer",
  "HIZ MOTORLU ARAÇLAR YEDEK PARÇA SAN.TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "HK GARAGE - HAYDAR KARACAN": "Eren Aykut",
  "HK OTOMOTİV YEDEK PARÇA - HAKAN ÖZDEMİR": "Ferhan Demir",
  "HK TUNİNG AUTOMOTİVE - ÖMER HAKAN FİLİZ": "Engin Alaca",
  "HK.YENİYOL YEDEK PARÇA AKSESUAR - HÜLYA KOZGÜL": "Ferhan Demir",
  "HYT OTOMOTİV NAKLİYE İNŞAAT SANAYİ TİCARET LTD.ŞTİ.": "Recep Yılmaz",
  "HZL HIZLI ARAÇ GIDA SAN.VE TİC.LTD.ŞTİ.": "Ferhan Demir",
  "HÜNKAR İNŞAAT TAAHHÜT OTOMOTİV TURİZM TİCARET LİMİTED ŞİRKETİ": "Onur Selvi",
  "HÜR OTO GARAGE - ÖZGÜR KÖY": "Eren Aykut",
  "HİDAYETOTO YEDEK PARÇA İÇ VE DIŞ TİC.A.Ş.": "Mustafa Koçalı",
  "HİKMET OTOMOTİV - TAHİR KAYA / ŞUBE 2": "Alpaslan Değer",
  "HİKMET OTOMOTİV JAPON KORE YEDEK PARÇALARI - TAHİR KAYA / ŞUBE": "Alpaslan Değer",
  "HİKMET OTOMOTİV RENAULT -TOFAŞ-ALMAN VE JAPON GR.YED.PARÇ.VE KAPR. AKSAMI - TAHİR KAYA": "Alpaslan Değer",
  "HİLAL SEGMAN": "Ferhan Demir",
  "HİMKA TEKSTİL OTOMOTİV İNŞAAT PETROL İTHALAT İHRACAT SAN.VE TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "HİS OTOMOTİV -  ONUR ONAT": "Ferhan Demir",
  "HİSAR OTO TAMİR VE BAKIM SERVİSİ - MEHMET KEKLİK": "Erbay Atlı",
  "HİSAR OTOMOTİV İNŞAAT TURİZM TİC.SAN.LTD.ŞTİ.": "Mustafa Koçalı",
  "IŞIKSER ISITMA SOĞUTMA SİST. İML. VE TAMİRAT - BAYRAM IŞIKVERİR": "Erbay Atlı",
  "JAPON AVRUPA OTO YEDEK PARÇA BÜLENT KIRIŞ VE BEKİR KIRIŞ ORTAKLIĞI": "Ömer Kınalı",
  "JAPON OTO SERVİSİ İNŞ.MÜH.TAAH.TURZ.SAN.VE TİC.LTD.ŞTİ.": "Sefa Akkan",
  "KAAN OTO MARKET YED.PARÇA ORJ.MEK.VE KAP.PARÇALARI - MERT YAVUZ": "Mustafa Koçalı",
  "KADA OTO RADYATÖRLERİ - SEZGİN TOSUN": "Ali Osman Demir",
  "KAHRAMAN OTO YEDEK PARÇA - BEKİR KAHRAMAN": "Cüneyt Baş",
  "KAHRAMAN TİC.OTO YED.PAR. - CEVDET KAHRAMAN": "Onur Selvi",
  "KAKİLLİOĞLU OTOM.İNŞ.TAAH.TUR.NAK.SAN.TİC.LTD.ŞTİ.": "Erbay Atlı",
  "KALE GRUP OTOMOTİV TİC.LTD.ŞTİ.": "Ferhan Demir",
  "KALE OTOMOTİV - SERCAN BAK": "Recep Yılmaz",
  "KALE OTOMOTİV YEDEK PARÇA LTD.ŞTİ.": "Serdar Parlakkan",
  "KAMA MOTORLU ARAÇLAR OTOMOTİV SAN.VE TİC.A.Ş.": "Cüneyt Baş",
  "KAMA MOTORLU ARAÇLAR OTOMOTİV SAN.VE TİC.A.Ş./ ŞUBE": "Cüneyt Baş",
  "KAMELYA OTOMOTİV SANAYİ VE TİC.LTD.ŞTİ.": "Ferhan Demir",
  "KAMEROĞLU OTO YEDEK PARÇA - TUNCAY KAYA": "Serdar Parlakkan",
  "KAMİLPAR OTOMOTİV - KAMİL ÇAĞŞAK": "Seçkin Ozan Akıllı",
  "KANARYA OTO SANAYİ VE TİCARET LTD.ŞTİ.": "Recep Yılmaz",
  "KANLIDERE OTOMOTİV - AHMET KANLIDERE": "Engin Alaca",
  "KAPLAN OTO YEDEK PARÇA VE AKSESUAR - UĞUR KAPLAN": "Engin Alaca",
  "KAPLAN OTOMOTİV SPARE PARTS - SÜLEYMAN KAPLAN": "Alpaslan Değer",
  "KAPORTA DÜNYASI - EMRE ÇAKMAK": "Alpaslan Değer",
  "KAPORTA PLUS -  SEFER İDİĞ": "Alpaslan Değer",
  "KAR-PA OTOMOTİV TİC.VE SAN.LTD.ŞTİ.": "Ömer Kınalı",
  "KARABAĞ MARKET - BAYRAM KARABAĞ": "Recep Yılmaz",
  "KARACA AUTO OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "KARACA OTOMOTİV GIDA NAKLİYE SANAYİ VE TİC. LTD.ŞTİ.": "Erbay Atlı",
  "KARACA OTOMOTİV YED.PARÇ. - HACI HALİL İBRAHİM KARACA": "Eren Ateş",
  "KARACABEY TİCARET - MUSTAFA KARACA": "Eren Ateş",
  "KARADAĞ OTO - OSMAN KARADAĞ": "Recep Yılmaz",
  "KARADENİZ OPEL YEDEK PARÇA LTD.ŞTİ.": "Ömer Kınalı",
  "KARADENİZ OTO VE TURİZM - RECEP DURMUŞ": "Mustafa Koçalı",
  "KARADENİZ OTOMOTIV YEDEK PARCA - EMRULLAH ELBİR": "Ömer Kınalı",
  "KARADENİZ OTOMOTİV YEDEK PARÇA - ADEM ERGÜLLÜ": "Mustafa Koçalı",
  "KARADENİZ PLUS OTOMOTİV TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "KARAKAŞ OTOMOTİV OTO YEDEK PARÇA - ALİ EKMEKÇİ": "Serdar Parlakkan",
  "KARAKAŞLAR OTO YEDEK PARÇA TUR.SAN.VE TİC.LTD.ŞTİ.": "Ferhan Demir",
  "KARAOPEL - KÜBRA KARADOĞAN": "Engin Alaca",
  "KARAÜZÜMLER OTOMOTİV - ALİ KARAÜZÜM": "Serdar Parlakkan",
  "KARCI OTOMOTİV - YUNUS EMRE KARCI": "Mustafa Koçalı",
  "KARCIOĞLU VOLKSWAGEN - VEDAT KARCIOĞLU": "Eren Ateş",
  "KARDEŞLER OTO RADYATÖR TAMİR VE BAKIM SERVİSİ - CENGİZ ORAL": "Ali Osman Demir",
  "KARDEŞLER OTOMOTİV - MEHMET ALİ KURT": "Alpaslan Değer",
  "KARMA OTO YEDEK PARÇA - HÜSEYİN KARAAHMETOĞLU": "Ömer Kınalı",
  "KARİYER OTO KLİMA SOĞUTMA VE ISITMA SİSTEMLERİ - ONUR TOHUM": "Ali Osman Demir",
  "KASIRGA ULUS.TAŞ.TUR.OTO YED.PAR.GID.TAR.VE PET.ÜRN.İTH.İHR.SAN.VE TİC.LTD.ŞTİ.": "Serdar Parlakkan",
  "KAYA KARDEŞLER TAŞIT OTO YED.PARÇ.SAN.VE TİC.LTD.ŞTİ.": "Alpaslan Değer",
  "KAYA RADYATÖR TURZ.İNŞ.İTH.VE İHR.SAN.TİC.LTD.ŞTİ.": "Ali Osman Demir",
  "KAYABAŞI ÖZEL FORD SEVİSİ - BAYRAM KAYABAŞI": "Onur Selvi",
  "KAYALAR PLUS OTOMOTİV SANAYİ TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "KAYALAR YAĞ OTOMOTIV INŞ IHR ITH PAZ SAN VE TIC LTD ŞTI.": "Cüneyt Baş",
  "KAYASAN OTOMOTİV MUHAMMET ÖMER KAYA KOLLEKTİF ŞTİ.": "Ferhan Demir",
  "KAZANCI SEGMAN OTOMOTİV İNŞ.SAN.TİC.İTH.VE İHR.LTD.ŞTİ./ İKİTELLİ": "Mustafa Koçalı",
  "KAZANCI TEM OTOMOTIV LTD.ŞTI.": "Mustafa Koçalı",
  "KAZANCIOĞLU OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Ferhan Demir",
  "KAZANÇLI OTOMOTİV SANAYİ VE TİC.LTD.ŞTİ.": "Ferhan Demir",
  "KAÇAR YEDEK PARÇA OTOMOTİV İNŞ.EM.SAN.TİC.LTD.ŞTİ.": "Engin Alaca",
  "KEMAL OTO - HAYDAR CEYHAN": "Ferhan Demir",
  "KEMAL OTO - HAYDAR CEYHAN / MASLAK": "Ferhan Demir",
  "KEMAL OTOMOTİV - HAYDAR CEYHAN": "Ferhan Demir",
  "KEMAL OTOMOTİV VE OTO YED.PAR. - YAHYA KIRKICI": "Serdar Parlakkan",
  "KEMALOĞLU ULUSLARARASI TAŞ.VE LOJ.HİZ.A.Ş.": "Recep Yılmaz",
  "KENAN YEDEK PARÇA PAZ.İTH.İHR.OTO.İNŞ.TUR.GID.SAN.VE TİC.LTD.ŞTİ.": "Sefa Akkan",
  "KEREM OTOMOTİV - KEREM HÜRER": "Ferhan Demir",
  "KEREM OTOMOTİV - YUNUS EMRE ALKAN": "Alpaslan Değer",
  "KILINÇ RADYATÖR - HİLMİ KILINÇ": "Ali Osman Demir",
  "KILIÇ OTOMOTİV YEDEK PARÇA SAN.İTH.İHR.TİC.LTD.ŞTİ": "Ferhan Demir",
  "KINACI OTOMOTİV GENEL SER.YED.PAR. - BİLAL KINACI": "Engin Alaca",
  "KIRDAN YAPI MÜHENDISLIK OTOMOTIV GAYRIMENKUL TAŞ.SAN.TİC LTD.ŞTİ": "Eren Ateş",
  "KIRIMLI MOTORLU ARAÇ.MÜH.İNŞ.ZÜC.SAN VE TİC.A.Ş.": "Engin Alaca",
  "KIRIMLI MOTORLU ARAÇ.MÜH.İNŞ.ZÜC.SAN VE TİC.AŞ": "Engin Alaca",
  "KIVANÇ OTO YEDEK PARÇA - KIVANÇ UZUNGENÇ": "Serdar Parlakkan",
  "KLAS OTO YEDEK PARÇA - RECEP İLHAN": "Engin Alaca",
  "KLIMAUTO YEDEK PARÇA SAN.VE TİC.LTD.ŞTİ.": "Ali Osman Demir",
  "KMR KAYALAR OTOMOTİV SAN. VE TIC. LTD. ŞTİ": "Serdar Parlakkan",
  "KOCADAĞ OTO RADYATÖR DÜNYASI - AHMET KOCADAĞ": "Ali Osman Demir",
  "KOCADAĞ OTO RADYATÖR DÜNYASI - FATMA KOCADAĞ": "Ali Osman Demir",
  "KOCAELİ RADYATÖR - UĞUR YILMAZ": "Ali Osman Demir",
  "KOCASİNAN BİRLİK OTOMOTİV SANAYİ VE DIŞ TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "KOMPAR MOTORLU ARAÇLAR SANAYİ VE TIC.LTD.STI": "Recep Yılmaz",
  "KONOPAL OTOMOTİV İNŞAAT VE GIDA PAZ.SAN.TİC.LTD.ŞTİ. / MERKEZ": "Cüneyt Baş",
  "KONOTO OTOMOTİV YEDEK PARÇA SAN.VE TİC.LTD.ŞTİ.": "Erbay Atlı",
  "KORKMAZ MOTORLU ARAÇLAR - RAMAZAN KORKMAZ": "Ferhan Demir",
  "KORKMAZ OTO - GİZEM KORKMAZ": "Engin Alaca",
  "KORKMAZ OTOMOTİV - MEHMET KORKMAZ": "Engin Alaca",
  "KOYUNCU OTOMOTİV - HÜSEYİN KOYUNCU ORT.": "Engin Alaca",
  "KOYUNCUOĞLU OTO KLİMA VE YDK.PRÇ. SAN. TIC. LTD. ŞTI.": "Cüneyt Baş",
  "KOZAN RADYATÖR - ADEM KOZAN": "Ali Osman Demir",
  "KOÇ DİREKSİYON OTOMOTİV SANAYİ TİCARET A.Ş.": "Cüneyt Baş",
  "KOÇ KARDEŞLER OTOMOTİV - CANER KOÇ": "Cüneyt Baş",
  "KOÇAK OTOMOTİV - SİNAN KOÇAK": "Ferhan Demir",
  "KOÇAK OTOMOTİV-EDİP EYİKOÇAK": "Alpaslan Değer",
  "KRN OTOMOTİV - KORAY ATALAY": "Recep Yılmaz",
  "KUSWA GROUP OTOM.OTO YED.PAR. SAN.VE TİC.LTD.ŞTİ.": "Onur Selvi",
  "KUTLU KARASAKAL OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "KUTLULAR OTO - HASAN KUTLU": "Engin Alaca",
  "KUZEY NRT OTOM.YED.PAR.İNŞ.SAN.VE DIŞ TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "KUZEY OTO - YUSUF SAYIN": "Mustafa Koçalı",
  "KUZEY OTO RADYATÖR BİLİŞİM - SERDAR ÇALIŞKAN": "Ali Osman Demir",
  "KUZEY OTO RADYATÖR HASAN YETİK ORT.": "Ali Osman Demir",
  "KÖKSAL OTOMOTİV - KÖKSAL AKYÜZ": "Serdar Parlakkan",
  "KÖSE OTOMOTİV  - KAMİL KÖSE VE ORT.": "Mustafa Koçalı",
  "KÖSE OTOMOTİV YEDEK PARCA - MUSTAFA KÖSE": "Onur Selvi",
  "KÜÇÜK VOLKSWAGEN MİDAT FİDAN VE OKTAY KARACA ADİ ORT.": "Sefa Akkan",
  "KÜÇÜKER OTOMOTİV - BAYRAM KÜÇÜKER": "Erbay Atlı",
  "LACİVERT OTO - MURAT TOPUZ": "Ferhan Demir",
  "LEON MAFIA - SUAT YILMAZ": "Eren Aykut",
  "LOKMAN OTOMOTİV YEDEK PARÇA - LOKMAN ERGÜNLÜ": "Mustafa Koçalı",
  "LOKMAN OTOMOTİV YEDEK PARÇA SANAYİ VE TİCARET LTD.ŞTİ.": "Ferhan Demir",
  "LOKMAN OTOMOTİV YEDEK PARÇA SANAYİ VE TİCARET LTD.ŞTİ. / ŞUBE": "Ferhan Demir",
  "LİDER OTOMOTİV YEDEK PARÇA - İDRİS KAVAN": "Eren Ateş",
  "M-Ş OTOMOTİV YED.PAR. - NAZMİYE ARSLAN": "Ferhan Demir",
  "MAD GARAGE - MUHAMMED EMİN DEMİR": "Eren Aykut",
  "MAHMUT OTO - MAHMUD ALEVİ": "Alpaslan Değer",
  "MAHİR CEVAT ŞEN ADİ ORT.": "Ömer Kınalı",
  "MAHİR GROUP OTOMOTİV İNŞAAT VE SAN.TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "MAKAS TİCARET OTO YED.PAR. - UFUK MAKAS": "Engin Alaca",
  "MAKASLI OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Engin Alaca",
  "MALATYA VATAN YEDİEMİN OTOP.OTOM.AKS.YED.PAR.TUR.SAN.TİC.LTD.ŞTİ.": "Alpaslan Değer",
  "MARKA GLOBAL OTOMOTİV YED.PAR.İTH.İHR.LTD.ŞTİ.": "Seçkin Ozan Akıllı",
  "MARKA OTOMOTİV - FİLİZ BAĞDAŞ": "Engin Alaca",
  "MARKA OTOMOTİV - MELİKE ÖZKAN": "Serdar Parlakkan",
  "MARLAND OTOMOTİV SANAYİ VE TİC.LTD.STİ.": "Serdar Parlakkan",
  "MARMARA OTOMOTİV - YILMAZ YILDIZ": "Recep Yılmaz",
  "MASBEK OTOMOTİV SAN.İÇ VE DIŞ TİC.LTD.ŞTİ.": "Erbay Atlı",
  "MASLAK YEDEK PARÇA OTO AKSESUARLARI İÇ VE DIŞ TİC.LTD.ŞTİ.": "Ferhan Demir",
  "MASMER OTOMOTİV YEDEK PARÇA - MUHAMMET ASLAN": "Ferhan Demir",
  "MAT MOTORLU ARAÇLAR LİMİTED ŞİRKETİ": "Recep Yılmaz",
  "MAT OTOMOTİV YEDEK PARÇA - ŞEMSİNUR AKBULUT": "Recep Yılmaz",
  "MAVİ YEDEK PARÇA OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "MCK MOTORS YEDEK PARÇA LTD.ŞTİ": "Recep Yılmaz",
  "MEFA OTO DOLAR": "Ferhan Demir",
  "MEGA TAŞIT YEDEK PARÇA SANAYİ TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "MEGA-TEK OTOMOTİV MAK.YED.PARÇ.TİC.VE SAN.LTD.ŞTİ.": "Sefa Akkan",
  "MEHMET BATMAN OTO YEDEK PARÇA TİC. İTH. İHR. LTD. ŞTİ.": "Serdar Parlakkan",
  "MEHMET CAN AYZİT": "Eren Aykut",
  "MEHMET KAPLAN OTO NAK.TUR.SAN.VE TİC.LTD.ŞTİ.": "Erbay Atlı",
  "MEK KARADAĞ OTOMOTİV YEDEK PARÇA SAN.VE TİC.LTD.ŞTİ.": "Engin Alaca",
  "MEKATRONİK OTO BAKIM ONARIM - SELAM ÇİFTÇİ": "Alpaslan Değer",
  "MEND OTOMOTİV TİC.LTD.ŞTİ.": "Ferhan Demir",
  "MENTEŞ OTO - FATİH MENTEŞ": "Engin Alaca",
  "MERCAN RADYATÖR SAN.VE TİC.LTD.ŞTİ": "Ali Osman Demir",
  "MERCANLAR OTOMOTIV TİCARET A.Ş. / ANTALYA": "Onur Selvi",
  "MERCANLAR OTOMOTİV TİC.A.Ş.": "Ferhan Demir",
  "MERCANLAR OTOMOTİV TİCARET A.Ş. / MERKEZ": "Mustafa Koçalı",
  "MERCANLAR OTOMOTİV TİCARET A.Ş. / İZMİR": "Sefa Akkan",
  "MERCANLAR OTOMOTİV TİCARET A.Ş./ KADOSAN": "Recep Yılmaz",
  "MERKEZ OPEL - BÜLENT ZOROĞLU": "Eren Ateş",
  "MERKEZ OTO - SELİM BİNGÖLLİ": "Mustafa Koçalı",
  "MERKEZ OTOMOTİV TİC.A.Ş.": "Cüneyt Baş",
  "MERSPAR OTOMOTİV LTD.ŞTİ.": "Serdar Parlakkan",
  "MERT OTO YEDEK PARÇA KAPORTA VE BOYA - MEHMET BAKİ DENERİ": "Alpaslan Değer",
  "MERT OTOMOTİV - AHMET NUH": "Serdar Parlakkan",
  "MERT YEDEK PARCA OTO İNŞAAT TURİZM SAN. TİC. LTD.ŞTİ.": "Ömer Kınalı",
  "MERT İNŞAAT OTOMOTİV - ZEKİ BOZ": "Erbay Atlı",
  "MERTLER HURDA OTO YEDEK PARÇA METAL PLASTİK İNŞAAT TURİZM SANAYİ VE TİC.LTD.ŞTİ.": "Sefa Akkan",
  "MERTTUĞ MAKİNA OTOMOTİV ELEKTRONİK MED.SER.HIR.TAAH.İTH.İHR.SAN.TİC.LTD.ŞTİ": "Eren Ateş",
  "MES YEDEK PARÇA OTOMOTİV TİC.VE SAN.LTD.ŞTİ.": "Engin Alaca",
  "MESUT OTOMOTİV - MESUT DEVECİ": "Ferhan Demir",
  "MET OTOMOTİV CHEVROLET OPEL YEDEK PARÇA - MURAT TAŞDEMİR": "Eren Ateş",
  "MET-PAR OTOMOTİV - YUSUF METİN": "Ferhan Demir",
  "META FORZA OTOMOTİV - MUSTAFA ÖNEM": "Sefa Akkan",
  "METEM RADYATÖR SAN. VE TİC. LTD. ŞTİ.": "Ali Osman Demir",
  "METSAM OTOMOTİV YED.PARÇ.SAN.VE TİC.LTD.ŞTİ.": "Sefa Akkan",
  "METİN KARDAŞ KARATAŞ OTOMOTİV YEDEK PARÇA İML.İTH.İHR.LTD.ŞTİ.": "Erbay Atlı",
  "METİN MOTORLU ARAÇLAR LTD ŞTİ.": "Seçkin Ozan Akıllı",
  "METİN OTOMOTIV AUTO JAPON - OPEL YEDEK PARÇALARI MERAL ALTUĞ": "Serdar Parlakkan",
  "METİN OTOMOTİV İNŞ. BİLG.LOJİSTİK E- TİCARET TUR. GIDA SAN VE TİC. LTD. ŞTİ.": "Ferhan Demir",
  "MF OTOMOTİV - FURKAN AYKUT": "Mustafa Koçalı",
  "MFK KAYA OTO YEDEK PARÇA SAN.VE TİC.LTD.ŞTİ.": "Serdar Parlakkan",
  "MGK RULMAN SANAYİ VE TİCARET A.Ş.": "Cüneyt Baş",
  "MIS OTOMOTİV YEDEK PARÇA - İHSAN SOYOĞLU": "Seçkin Ozan Akıllı",
  "MIZRAK OTOMOTİV YEDEK PARÇA - YUSUF MİZRAK": "Alpaslan Değer",
  "MKS OTOMOTİV YEDEK PARÇA - ŞAKİR SANTÜRK": "Serdar Parlakkan",
  "MM TUNİNG - MUSTAFA UZUN": "Eren Ateş",
  "MODA CARS - BERKAN BULUT": "Onur Selvi",
  "MRK OTOMOTİV TİCARET SANAYİ LTD.ŞTİ.": "Cüneyt Baş",
  "MRLEOPART OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "MSA GRUP OTOMOTİV İNŞAAT NAKL.SAN.VE TİC.LTD.ŞTİ.": "Alpaslan Değer",
  "MSN AUTO PARTS OTOMOTİV VE İTH.İHR.SAN.TİC.LTD.ŞTİ.": "Ferhan Demir",
  "MSTGARAJ - MUSTAFA KÜÇÜKCİVİL": "Erbay Atlı",
  "MTS OTO ÖZEL SERVIS OTOMOBIL BAK.HIZM. -ÖZKAN ABACI": "Recep Yılmaz",
  "MUHSİN ŞEVLUK": "Ferhan Demir",
  "MURAT ALTUN RADYATÖR KLİMA BAKIM TAMİRİ - MURAT ALTUN": "Ali Osman Demir",
  "MURAT DOĞAN": "Ferhan Demir",
  "MURAT OTO KLİMA - DENİZ CAN": "Ali Osman Demir",
  "MURAT OTOMOTİV - MURAT SADE": "Engin Alaca",
  "MURAT ŞAHİN": "Mustafa Koçalı",
  "MUSPA BESİCİLİK OTOMOTİV GIDA İNŞ.SAN.VE TİC.LTD.ŞTİ.": "Alpaslan Değer",
  "MUSPAR OTOMOTİV - MUSTAFA YILDIZ": "Ferhan Demir",
  "MUSPAR OTOMOTİV YED.PARÇ. - MUSTAFA DÜLGER": "Engin Alaca",
  "MUSTAFA KALEM": "Seçkin Ozan Akıllı",
  "MUSTAFA KISACIK": "Ferhan Demir",
  "MY BOSS OTOMOTİV TUR. İNŞ. ELEKTK. METAL İTH.İHR.SAN.VE TİC.LTD.ŞTI.": "Eren Ateş",
  "MYK OTO YEDEK PARÇA - YUSUF OKTAY": "Ferhan Demir",
  "MYPAR OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "MÜHENDİS OTOMOTİV YED.PARÇ.TİC.LTD.ŞTİ.": "Sefa Akkan",
  "MİNA GRUP OTOMOTİV SAN.LTD.ŞTİ.": "Recep Yılmaz",
  "MİNİK GARAGE - SÜLEYMAN SARIKAYA": "Eren Aykut",
  "MİR SOĞUTMA OTO YEDEK PARÇA LTD.ŞTİ.": "Ferhan Demir",
  "MİRAJ OTOMOTİV İTHALAT İHRACAT - SERAP YAVUZ": "Sefa Akkan",
  "MİRHAN OTOMOTİV - HALİL UGUN": "Alpaslan Değer",
  "MİRZA OTOMOTİV - OSMAN ELİBOL": "Recep Yılmaz",
  "MİZAN AUTO - ÖMER PATLAK": "Serdar Parlakkan",
  "NAM OTOMOTİV SERVİS YEDEK PARÇA SAN. VE TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "NAR YEDEK PARÇA OTOMOTİV SAN.VE TİC.A.Ş.": "Cüneyt Baş",
  "NAR YEDEK PARÇA OTOMOTİV SANAYİ VE TİC.A.Ş. - 2": "Cüneyt Baş",
  "NAZ OTOMOTİV - SEDAT YAŞAR": "Mustafa Koçalı",
  "NAİMOĞLU OTOMOTİV YEDEK PARÇA SAN.TİC.LTD.ŞTİ.": "Alpaslan Değer",
  "NAİMOĞLU YEDEK PARÇA - GÜLSEREN DENİZ": "Alpaslan Değer",
  "NESE OTOMOTİV İTH.İHR.LTD.ŞTİ": "Mustafa Koçalı",
  "NETOTO YEDEK PARÇA - MURAT BEDİR": "Recep Yılmaz",
  "NSR OTOMOTİV YEDEK PARÇA TEKS.SAN.VE TİC.LTD.ŞTİ.": "Sefa Akkan",
  "NUR OPEL OZEL SERVİS -  MEHMET KARAOĞLU": "Sefa Akkan",
  "NUR-PAR OTO YEDEK PARÇA PAZ.SAN.VE TİC.LTD.ŞTİ. / ŞUBE": "Cüneyt Baş",
  "NUR-PAR OTO YEDEK PARÇA PAZARLAMA SAN.VE TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "NUREL OTO RADYATÖR SOĞUTUCU - MURAT ULUKÜTÜK": "Ali Osman Demir",
  "NURŞEN GAZİ OTOMOTİV YEDEK PARÇA TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "NÖM-MAK MÜH.İNŞT.ELKJ.SAN.TİC.LTD.ŞTİ.": "Ali Osman Demir",
  "NÜANS YEDEK PARÇA OTOMOTİV SANAYİ VE DIŞ TİC. LTD. ŞTİ.": "Ferhan Demir",
  "NİLSER OTO YEDEK PARÇA - KAAN KARTAL": "Sefa Akkan",
  "NİLÜFER OTOMOTİV - MAHMUT POLATKALASI": "Engin Alaca",
  "NİĞPAR OTO YEDEK PARÇA - YUNUS EMRE YÜCEER": "Erbay Atlı",
  "OBK OTO BAKIM SANAYİ VE TİC.LTD.ŞTİ.": "Ferhan Demir",
  "OEM AUTO PARTS OTOMOTİV SAN.TİC.LTD.ŞTİ.": "Erbay Atlı",
  "OEM CAR PARTS - ERDEM GÖLBAŞI": "Eren Ateş",
  "OFG OTO KLİMA YEDEK PARÇA - ÖMER FARUK GÜLER": "Ali Osman Demir",
  "OMY OTOMOTİV LTD. ŞTİ.": "Recep Yılmaz",
  "ON-KA OTOMOTİV SAN.TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "ONAY OTOMOTİV TUR.TAŞ.SAN.VE TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "ONLAR GROUP MOTORLU ARAÇLAR İNŞ.SAN.TİC.LTD.ŞTİ.": "Sefa Akkan",
  "ONLINE ARAÇ HİZMETLERİ OTO YED PARÇA SAN VE TİC.LTD.ŞTİ. BASIN EKSPRES": "Mustafa Koçalı",
  "ONLINE ARAÇ HİZMETLERİ OTO YED PARÇA SAN VE TİC.LTD.ŞTİ. ESENYURT": "Mustafa Koçalı",
  "ONLINE ARAÇ HİZMETLERİ OTO YED PARÇA SAN VE TİC.LTD.ŞTİ. KOCASİNAN": "Mustafa Koçalı",
  "ONLİNE YEDEK PARCA OFİSİ - GÖKALP YILMAZ": "Engin Alaca",
  "ONSAL GRUP OTOMOTİV VE YEDEK PARÇA SANAYİ TİC. LTD.ŞTİ.": "Ali Osman Demir",
  "ONUR BÜKTE": "Recep Yılmaz",
  "ONUR OTO - VOLKAN DURUKAN": "Ferhan Demir",
  "ONUR OTO RADYATÖR - ONUR ERAY": "Ali Osman Demir",
  "ONUR OTO VOLKSWAGEN - ONUR FEVZİ GÜNGÖREN": "Sefa Akkan",
  "ONUR OTOMOTİV - ALAETTİN BAKICI": "Onur Okumuş",
  "ONUR OTOMOTİV - MEHMET ONUR KAHRAMAN": "Sefa Akkan",
  "ONUR OTOMOTİV - İSMAİL DOĞAN": "Mustafa Koçalı",
  "OPAD YEDEK PARÇA TED.VE TİC.LTD.ŞTİ.": "Serdar Parlakkan",
  "OPEL CENTER - HAMİYET DURKUT": "Seçkin Ozan Akıllı",
  "OPEL MARKET - MUHAMMED AVCI": "Onur Selvi",
  "OPEL MARMARA OTO YEDEK PARÇA - NURCAN ÜNAL": "Mustafa Koçalı",
  "OPELPAR OTOMOTİV SAN.VE TİC.LTD.ŞTİ  / İVEDİK": "Eren Ateş",
  "OPELPAR OTOMOTİV SAN.VE TİC.LTD.ŞTİ. / BAŞKENT": "Eren Ateş",
  "OPELPAR OTOMOTİV SAN.VE TİC.LTD.ŞTİ. / MERKEZ": "Eren Ateş",
  "OPKAR OTOMOTİV - MUSA ARPACI": "Ömer Kınalı",
  "OPMAR OTO YEDEK PARÇA İNŞ.TAR.HAY.SAN.VE TİC.LTD.ŞTİ.": "Serdar Parlakkan",
  "OPSA OTOMOTİV SANAYİ VE TİC.LTD.ŞTİ.": "Sefa Akkan",
  "OPSER OTO - AZMİ AKMAN-ALİ KAAN KARAHAN ADİ ORTAKLIĞI": "Onur Selvi",
  "OPSER OTOMOTİV SAN.VE TİC.LTD.ŞTİ./MASLAK": "Ferhan Demir",
  "OPSER OTOMOTİV İNŞ.SAN.VE.TİC.LTD.ŞTİ./İKİTELLİ": "Mustafa Koçalı",
  "OPTİM ORJİNAL YEDEK PARÇA - ENES ÜLKER": "Ömer Kınalı",
  "OPTİM PSA ORİJİNAL YED.PAR. - EMRE ÜLKER": "Ömer Kınalı",
  "OPİM OTOMOTİV ÜRÜNLERİ MURAT YİĞİT İSMAİL DALMAZ ORT.": "Sefa Akkan",
  "ORHAN KORAY OTOMOTIV YEDEK PARÇA SANAYI VE TICARET LTD.ŞTI": "Mustafa Koçalı",
  "ORHAN KORAY OTOMOTIV YEDEK PARÇA SANAYI VE TICARET LTD.ŞTİ./ ŞUBE": "Mustafa Koçalı",
  "ORHAN TUNİNG - YUSUF HAN KURA": "Eren Aykut",
  "ORJİNAL OTO OPEL CHEVROLET ÇIKMA YEDEK PARÇA - HULİSİ KÖSEOĞLU": "Recep Yılmaz",
  "ORJİNAL OTO OPEL CHEVROLET ÇIKMA YEDEK PARÇA HULİSİ KÖSEOĞLU VE FURKAN ALPAN ADİ ORTAKLIĞI": "Recep Yılmaz",
  "ORJİNAL RADYATÖR VE EKSOZ TAMİR YENİLEME SERVİSİ - HALİL DAL": "Ali Osman Demir",
  "ORPA OTOMOTİV NAK. TUR.İNŞ.TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "ORPEL OTOMOTİV ORJ.VE İTHAL YEDEK PARÇA - ORHAN OKUŞLUĞ": "Alpaslan Değer",
  "ORTAŞ OTOMOTİV TEKS.İNŞ.GIDA SAN VE DIŞ TİC.LTD.ŞTİ": "Ömer Kınalı",
  "OSMANLI OPEL TAMİR BAKIM YEDEK PARÇA - CEVAT HALICI": "Mustafa Koçalı",
  "OSMANİYE COŞKUN OTO SANAYİ TİC.LTD.ŞTİ.": "Serdar Parlakkan",
  "OTO 19 - KADİR DEMİRKOPARAN": "Recep Yılmaz",
  "OTO 2000 OTOMOTİV TURİZM GIDA VE İNŞ.SAN.TİC.LTD.ŞTİ": "Recep Yılmaz",
  "OTO AK OTOMOTİV SAN. VE TİC. LTD. ŞTİ.": "Ali Osman Demir",
  "OTO AKABE OTOMOTİV PETR.ÜR.HUR.HAY.İNŞ.TAAH.TİC.SAN.LTD.ŞTİ.": "Ömer Kınalı",
  "OTO AKYIL YEDEK PARÇA - HASAN COŞAR": "Eren Ateş",
  "OTO ALINMIŞLAR RULMAN KAYIŞ VE YEDEK PARÇA SAN.TIC.LTD.ŞTI.": "Alpaslan Değer",
  "OTO ALMAN - AHMET MUTLU": "Ömer Kınalı",
  "OTO ALMAN OTOMOTİV SAN.TİC.İTH.VE İHR.LTD.ŞTİ.": "Seçkin Ozan Akıllı",
  "OTO ALP YEDEK PARÇA SANAYİ TİCARET LTD.ŞTİ.": "Engin Alaca",
  "OTO AR KUTLUK DİRİK VARİSLERİ ADİ ORTAKLIĞI": "Sefa Akkan",
  "OTO ASLANLAR YEDEK PARÇA HÜSAMETTİN ASLAN": "Engin Alaca",
  "OTO ASLANLAR YEDEK PARÇA HÜSAMETTİN ASLAN / ŞUBE": "Engin Alaca",
  "OTO ASYA - CEVDET OKUKCU": "Ferhan Demir",
  "OTO ATİK OTO YEDEK PARÇA TİC VE SAN.LTD.ŞTİ.": "Ferhan Demir",
  "OTO AYHAN AVRUPA YEDEK PARÇA TİCARET - BERİL ATAK": "Mustafa Koçalı",
  "OTO AYSELLER MUHSİN AYSEL MUSTAFA AYSEL ORTAKLIĞI": "Eren Ateş",
  "OTO BAKIRCI KARDEŞLER - HACI AHMET BÜYÜKBAKIRCI": "Seçkin Ozan Akıllı",
  "OTO BAYBARS MURAT TÜRKMEN VOLKSVAGEN - AUDİ - OTO YED.PAR.": "Sefa Akkan",
  "OTO BEKŞAN -MUAMMER BEKTAŞ": "Recep Yılmaz",
  "OTO BEKŞAN- MUAMMER BEKTAŞ / ŞUBE": "Recep Yılmaz",
  "OTO BERKAN - TEZCAN BAŞMERGEN": "Ferhan Demir",
  "OTO BEŞ - BAYRAM ŞİŞMAN": "Ömer Kınalı",
  "OTO BULUŞ DIŞ TİCARET LTD.ŞTİ.": "Erbay Atlı",
  "OTO BUTİK - YASİN SERİN": "Erbay Atlı",
  "OTO BÜLENT AZİM MOTOR YENİLEME OTO YEDEK PARÇA İNŞAAT VE İTHALAT İHRACAT LİMİTED ŞİRKETİ": "Alpaslan Değer",
  "OTO BİLGİÇ - ÜMİT BİLGİÇ": "Ferhan Demir",
  "OTO BİRLİK OTOMOTIV SERVIS HIZMETLERI NAKLIYE VE GIDA TIC LTD STI": "Sefa Akkan",
  "OTO CUMHUR - CUMHUR YALABIK": "Sefa Akkan",
  "OTO DEMİR DIŞ TİC A.Ş./ BURSA": "Engin Alaca",
  "OTO DEMİR DIŞ TİC.A.Ş.": "Mustafa Koçalı",
  "OTO DENİZ - MURAT BALK": "Seçkin Ozan Akıllı",
  "OTO DENİZ MÜHENDİSLİK YEDEK PARÇA SAN.VE TİC.LTD.ŞTİ.": "Seçkin Ozan Akıllı",
  "OTO DENİZ MÜHENDİSLİK YEDEK PARÇA SAN.VE TİC.LTD.ŞTİ. - ŞUBE": "Seçkin Ozan Akıllı",
  "OTO DOKUYAN - HÜSEYİN DOKUYAN": "Ömer Kınalı",
  "OTO DOĞU TİCARET VE SANAYİ A.Ş.": "Cüneyt Baş",
  "OTO DOĞU TİCARET VE SANAYİ A.Ş. / ŞUBE": "Cüneyt Baş",
  "OTO DÜZDÖL RADYATÖR TAMİR ATÖLYESİ - SELAMİ DÜZDÖL": "Ali Osman Demir",
  "OTO ECZANE YED.PAR. - ZEYNEP AYDİNÇ": "Serdar Parlakkan",
  "OTO ELİF - HÜSEYİN ÖMÜR BÜYÜKÖZDEMİR": "Erbay Atlı",
  "OTO EMRE OTOMOTİV YEDEK PARÇA VE TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "OTO ERBAY OTOMOTİV SANAYİ VE TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "OTO ERDAL - ERDAL COŞKUN": "Mustafa Koçalı",
  "OTO ERKAN - ESENGÜL KORKMAZ": "Ömer Kınalı",
  "OTO FAHRİ AMERİKAN OTO YEDEK PARÇA - FAHRİ LAFÇI": "Ali Osman Demir",
  "OTO FATİH ARAÇ YEDEK PARÇALARI SAN.VE TİC.LTD.ŞTİ.": "Alpaslan Değer",
  "OTO GÖNÜL OTOMOTIV INŞAAT SANAYI TIC. LTD. ŞTI.": "Sefa Akkan",
  "OTO GÜL - CANER GÜL": "Ömer Kınalı",
  "OTO GÜL YEDEK PARÇA - HALİT GÜL": "Ömer Kınalı",
  "OTO GÜVEN OPEL - RECEP ARIKAN": "Eren Ateş",
  "OTO HAKAN - HAKAN KAYA ADİ ORTAKLIĞI": "Ömer Kınalı",
  "OTO HÜSEYİN YED.PARÇ.ULUS.TAŞ.NAK.MOB.SAN VE TİC.LTD.ŞTİ.": "Sefa Akkan",
  "OTO KARABİNA OTOMOTİV SAN.TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "OTO KARABİNA OTOMOTİV SAN.TİC.LTD.ŞTİ./ ŞUBE": "Ömer Kınalı",
  "OTO KEREM - BEKİR YILMAZ": "Mustafa Koçalı",
  "OTO KURT YEDEK PARÇA - İBRAHİM KURT": "Mustafa Koçalı",
  "OTO KÜÇÜK OTO YEDEK PARÇALARI - NURULLAH TONGUZ": "Erbay Atlı",
  "OTO MAHİR - RENAN BAŞAVCI": "Ali Osman Demir",
  "OTO MARKET - SEFA MARAL": "Ömer Kınalı",
  "OTO MARKET İÇ VE DIŞ TİC.MOTORLU ARAÇLAR YED.PAR.MAD.YAĞ.ÜRN. SAN.LTD.ŞTİ.": "Alpaslan Değer",
  "OTO MARMARA OTOMOTİV İNŞ.GIDA TEKS.SAN.TİC.LTD.ŞTİ./ OTO MARKET ŞUBE": "Recep Yılmaz",
  "OTO MARMARA OTOMOTİV İNŞ.GIDA TEKS.SAN.TİC.LTD.ŞTİ./ PENDİK": "Recep Yılmaz",
  "OTO MARMARA OTOMOTİV İNŞ.GIDA TEKS.SAN.TİC.LTD.ŞTİ./YEDPA": "Recep Yılmaz",
  "OTO MEKANİK-LAZARİ KOSTANTİNİDİS": "Recep Yılmaz",
  "OTO NEBİ - AYŞE CENGİZ": "Seçkin Ozan Akıllı",
  "OTO OSMAN - OSMAN AYNA": "Cüneyt Baş",
  "OTO PİNAL - ÜNAL BARLAS VE ORT.": "Recep Yılmaz",
  "OTO RADYATÖR DÜNYASI - DİLCAN YİĞİTER": "Ali Osman Demir",
  "OTO RADYATÖR DÜNYASI - DİLCAN YİĞİTER / İSKENDERUN": "Ali Osman Demir",
  "OTO REKOR TURZ.YEDEK PARÇA SAN.VE TİC.LTD.ŞTİ.": "Ferhan Demir",
  "OTO REİS - REİS KİRAZ": "Mustafa Koçalı",
  "OTO SARIKAYA YEDEK PARÇA - HACI SARIKAYA": "Erbay Atlı",
  "OTO SAYGIN OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "OTO SAÇAKLI YEDEK PARÇA - YUNUS EMRE SAÇAKLI": "Alpaslan Değer",
  "OTO SAĞLAM - NECMETTİN SAĞLAM": "Mustafa Koçalı",
  "OTO SENTEZ ÇIKMA & YENİ YEDEK PARÇA - MUSTAFA KOLOĞLU": "Onur Selvi",
  "OTO SERHAT GRUP OTO.TİC.VE SAN.LTD.ŞTİ.": "Seçkin Ozan Akıllı",
  "OTO SERKAN OTOMOTİV YEDEK PARÇA SAN.VE TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "OTO SERKAN YEDEK PARÇA SAN.TİC.LTD.ŞTİ.": "Serdar Parlakkan",
  "OTO SESLİ YEDEK PARÇA-SERV.BAK.HİZM.SAN.VE TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "OTO SESLİ YEDEK PARÇA-SERV.BAK.HİZM.SAN.VE TİC.LTD.ŞTİ. - ALPARSLAN ŞUBE": "Ömer Kınalı",
  "OTO SPORT - HALİL YÜKSEL": "Eren Ateş",
  "OTO SÜLEYMAN - TURGUT DEMİR VE ORTAKLARI": "Ömer Kınalı",
  "OTO SİNCAN - MURAT CAN": "Eren Ateş",
  "OTO VURAL - MUSTAFA ZİHNİ EKMEKÇİOĞLU": "Ömer Kınalı",
  "OTO YASİN - YASİN KAYNAK": "Erbay Atlı",
  "OTO YASİNLER TİC.VE SAN.LTD.ŞTİ.": "Ferhan Demir",
  "OTO YED PAR - AHMET KARABİNA": "Ömer Kınalı",
  "OTO YEDEK PARÇA TİC. - ADNAN EMRE": "Onur Selvi",
  "OTO YILMAZ OTOMOTİV TUR.TAŞ.TEKS.SAN.LTD.ŞTİ.": "Mustafa Koçalı",
  "OTO YURTTAŞLAR AKÜ VE OTO YEDEK PARÇA - HARUN AKDENİZ": "Eren Ateş",
  "OTO YUSUF ESKİ OTO ALIM-SATIMI VE YED. PARÇ. TİC.-YUSUF DÖNDÜ": "Eren Ateş",
  "OTO ÇAKIR - ŞİNASİ ÇAKIR": "Ferhan Demir",
  "OTO ÖMER DIŞ TİCARET - HASAN KURT": "Ferhan Demir",
  "OTO ÖZKAN - ÖZKAN OCAK": "Ömer Kınalı",
  "OTO ÖZLEM YEDEK PARÇA - YILMAZ ÖKSÜZ": "Sefa Akkan",
  "OTO İBRAHİM OTO YEDEK PARÇA SAN.VE TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "OTO İKMAL KOLL.ŞTİ OTO SERVİS YEDEK PARÇA - MUZAFFER ÇUHADAR": "Ömer Kınalı",
  "OTO İNAN OTOMOTİV YEDEK PARÇA LAS.EM.NAK.İNŞ.TUR.SAN.VE TİC.LTD.ŞTİ.": "Seçkin Ozan Akıllı",
  "OTO İPEK YEDEK PARÇA - MURAT İPEK": "Eren Ateş",
  "OTO İZZET SAN. TİC. LTD.ŞTİ.": "Eren Ateş",
  "OTO ŞAH - MUSTAFA BALTACI": "Alpaslan Değer",
  "OTO ŞAHİN  - ŞAHİN UMA": "Alpaslan Değer",
  "OTOHAN ORJİNAL & İTHAL YEDEK PARÇA - HALİL CENGİZHAN": "Alpaslan Değer",
  "OTOKENT YEDEK PARÇA LTD.ŞTİ.": "Erbay Atlı",
  "OTOMOTİV PARÇASI - AHMET OĞUZ CAYMAZ": "Cüneyt Baş",
  "OTOPARS YEDEK PARÇA TİC.LTD.ŞTİ.": "Sefa Akkan",
  "OTORADYATÖR DÜNYASI OTOMOTİV İNŞ.PET.ÜR.GIDA TUR.SAN.VE TİC.LTD.ŞTİ.": "Ali Osman Demir",
  "OTORİNGO OTOMOTİV TURİZM LTD.ŞTİ. / DEPO": "Cüneyt Baş",
  "OTORİTE - İZZEDDİN ASLANOĞLU": "Recep Yılmaz",
  "OTOYILMAZ YEDEK PARÇA VE SERV.HİZM.TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "OTOŞEN MOTORLU ARAÇLAR TRZM SAN.TİC.LTD.ŞTİ.": "Engin Alaca",
  "OTTOCAR YEDEK PARÇA OTOMOTİV SANAYİ VE TİC.LTD.ŞTİ.": "Erbay Atlı",
  "OZAN OPEL SERVİSİ - OĞUZ OZAN": "Recep Yılmaz",
  "OZN OTOMOTİV VE YEDEK PARÇA - OZAN YILMAZ": "Recep Yılmaz",
  "PAN ANAHTAR - SADIK BÜYÜKKÜTÜK": "Ferhan Demir",
  "PAR VASS OTOMOTİV - MUSTAFA TÜRKÇÜER": "Erbay Atlı",
  "PARCOM OTOMOTİV SANAYİ TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "PARMAR OTOMOTİV İNŞAAT SANAYİ VE TİCARET LİMİTED ŞİRKETİ": "Onur Selvi",
  "PARS OTOMOTİV - CANAN DALDAL": "Eren Ateş",
  "PARSAN OTOMOTİV SAN.VE TİC.LTD.ŞTİ./ KADOSAN": "Recep Yılmaz",
  "PARSAN OTOMOTİV SN.VE TİC.LTD.ŞTİ./ ÜMRANİYE": "Recep Yılmaz",
  "PARSKAR MOT.ARAÇ.SAN.VE TİC.LTD.ŞTİ.": "Seçkin Ozan Akıllı",
  "PARSON OTOMOTİV SANAYİ DIŞ TİC.A.Ş.": "Ferhan Demir",
  "PART ASSİST OTO YEDEK PARÇA VE SER.HİZM.TİC.LTD.ŞTİ.": "Ferhan Demir",
  "PARTECH TOPTAN OTO YEDEK PARÇA LTD.ŞTİ.": "Eren Ateş",
  "PARÇA DÜNYASI - SEMİH CAN GÜNEŞ": "Alpaslan Değer",
  "PARÇA PİYASASI - SALİH BABÜR": "Ferhan Demir",
  "PARÇAARA OTOMOTİV İNTERNET HİZMETLERİ İNŞAAT TAAHHÜT SAN.TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "PARÇACIM PLUS - ADİL ÖZDEMİR": "Sefa Akkan",
  "PARÇAM OTOMOTİV TİCARET LTD.ŞTİ.": "Onur Selvi",
  "PARÇAOFİSİ OTOMOTİV BİLİŞİM HİZM.SAN.VE TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "PASLIOĞLU OTOMOTİV-MEHMET PASLIOĞLU": "Seçkin Ozan Akıllı",
  "PAUL LED XENON - AZİZ ARAP TUTUMLUOĞLU": "Eren Aykut",
  "PAYAM RADYATÖR OTO RADYATÖR VE KALORİFER PETEK ÇEŞ.- FATİH PAYAM": "Ali Osman Demir",
  "PEKER OROMOTİV YEDEK PARÇA - ENGİN PEKER / ŞUBE": "Engin Alaca",
  "PEKER OTOMOTİV YEDEK PARÇA-ENGİN PEKER": "Sefa Akkan",
  "PEKSEN OTOMOTİV - MEHMET YILDIZ": "Onur Selvi",
  "PELİT OTOMOTİV - HAVVA YERLİKAYA": "Recep Yılmaz",
  "PERAKENDE EURO": "Cüneyt Baş",
  "PERAKENDE TL": "Cüneyt Baş",
  "PERAKENDE TL - PERSONEL ÇIKIŞ HESABI": "Cüneyt Baş",
  "PERAKENDE USD": "Cüneyt Baş",
  "PINAR OTOMOTİV OTO YEDEK PAR.TOP.PER.SAT. - EMRE AKPINAR": "Onur Selvi",
  "PINAR OTOMOTİV VE SERVİS HİZMETLERİ TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "POLAT OTO SANAYİ VE TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "POLATLAR OTOMOTİV SAN.TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "PORMAS OTOMOTİV YEDEK PARÇA SAN VE TİC.LTD.ŞTİ": "Ferhan Demir",
  "POYRAZOĞLU GROUP OTOM.SAN.VE TİC.LTD.ŞTİ.": "Onur Okumuş",
  "POZİTİF OTOMOTİV YEDEK PARÇA SAN. VE TİC. LTD. ŞTİ / ŞUBE": "Cüneyt Baş",
  "POZİTİF OTOMOTİV YEDEK PARÇA ÜRETİMİ SAN.VE TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "PREMİER OTO YAN.SAN.İTH.İHR.TİC.LTD.ŞTİ.": "Engin Alaca",
  "PRESTİJ OTOMOTİV - YUNUS EMRE KASAP": "Ömer Kınalı",
  "PROCAR TUNİNG OTOMOTİV YEDEK PARÇA TİC. LTD. ŞTİ.": "Onur Selvi",
  "PROF PAR OTOMOTİV YEDEK PARÇA LTD.ŞTİ.": "Ferhan Demir",
  "PROPAR GRUP OTOM.YED.PAR.PAZ.VE İNŞ.TİC.LTD.ŞTİ.": "Seçkin Ozan Akıllı",
  "PROPARK OTOMOTİV TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "PSA OTOMOTİV - HASAN ŞAHİN": "Mustafa Koçalı",
  "PSA OTOMOTİV DIŞ TİC.LTD.ŞTİ.": "Ferhan Demir",
  "PSA OTOMOTİV DIŞ TİC.LTD.ŞTİ. / ŞUBE": "Ferhan Demir",
  "PSA PREMIUM - İSHAK DOĞAN": "Alpaslan Değer",
  "PİLOT GARAGE - MUSTAFA HİZARCI": "Recep Yılmaz",
  "PİNUKS OTOMOTİV İTHALAT VE İHR.SAN.TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "RADEL OTOMOTİV - HATİCE BASIR": "Ali Osman Demir",
  "RADYATÖRCÜ BÜLENT OTO RADYATÖR TAMİRİ - BÜLENT TUNÇKOL": "Ali Osman Demir",
  "RAFET OTOMOTİV YEDEK PARÇA SAN.VE TİC.LTD.ŞTİ.": "Engin Alaca",
  "RAHMAN YEDEK PARÇA OTOMOTİV TİC.LTD.ŞTİ.": "Ferhan Demir",
  "RALLİ MOTORLU ARAÇLAR OTOMOTİV YEDEK PARÇA İTH.İHR.SAN.TİC.LTD.ŞTİ.": "Seçkin Ozan Akıllı",
  "RAMAZAN KARAKUZU OTOMOTİV GIDA İNŞ.PAZ.SAN.VE TİC.LTD.ŞTİ.": "Erbay Atlı",
  "RAMTAŞ OTOMOTİV PETROL ÜRÜN.PAZ.SAN.TİC.LTD.ŞTİ.": "Erbay Atlı",
  "RAS-PAR OTOMOTİV - RAMAZAN DOĞAN": "Alpaslan Değer",
  "RATA TUNİNG - ÖZKAN ATAR": "Eren Aykut",
  "REALVOLKS OTO YEDEK PARÇA SAN.VE TİC.LTD.ŞTİ.": "Alpaslan Değer",
  "RECAR DIŞ TİCARET VE OTOM.YE.PAR.TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "RECAR OTO YEDEK PARÇA - SERAP EKİNCİ GÖKBURUN": "Recep Yılmaz",
  "REFİKA İLTİFAT ESKİÇAKIT": "Serdar Parlakkan",
  "RES-PAR OTO YEDEK PARÇA - MUSTAFA ÖZKARA": "Erbay Atlı",
  "REİS GRUP MİMARLIK İNŞ.SAN.TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "REİS OTO - ERSAN GÜN": "Ali Osman Demir",
  "REİS OTO TAMİR VE BAKIM SERVİSİ - MURAT DÖNMEZ": "Ömer Kınalı",
  "REİS VOLKSWAGEN - BEKİR BAYINDIR": "Eren Ateş",
  "RK OTO YEDEK PARÇA SANAYİ VE TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "RMT OTOMOTİV - CELALETTİN SALTIK": "Ali Osman Demir",
  "ROBUST PARTS OTOMOTİV SANAYİ VE TİC. LTD. ŞTİ.": "Engin Alaca",
  "ROD ORGANIZASYON YED.PARÇ. BAKIM VE ONARIM MERKEZI - RECEP DEMİRKAN": "Recep Yılmaz",
  "ROTA KONFOR OTOMOTİV SANAYİ TİC.LTD.ŞTİ.": "Ferhan Demir",
  "ROTA YEDEK PARÇA MOT.ARÇ.İTH.İHR.SAN.TİC.LTD.ŞTİ.": "Eren Ateş",
  "RSM WOLKSTEK OTOMOTİV İNŞAAT LTD.ŞTİ.": "Eren Ateş",
  "RTK MOTORLU ARAÇLAR DIŞ TİCARET A.Ş.": "Recep Yılmaz",
  "RÜZGAR OTO YEDEK PARÇA - MURAT BÜYÜKGÜLER": "Engin Alaca",
  "RÜZGAR OTOMOTİV YEDEK PARÇA - AHMET KAYA": "Ferhan Demir",
  "SABMATE OTOMOTİV YED.PAR.İTH.İHR.VE PAZ.A.Ş.": "Ferhan Demir",
  "SADE OTOMOTİV - ALİ AKMAN": "Sefa Akkan",
  "SAFİR TAMPON FAR - MUSTAFA YILMAZ": "Alpaslan Değer",
  "SAKARYA BALKAN MOTORLU ARAÇLAR TİC. VE SAN.LTD.ŞTİ.": "Engin Alaca",
  "SAMET KILINÇ OTOMOTİV SANAYİ VE TİCARET LİMİTED ŞİRKETİ": "Alpaslan Değer",
  "SAMSUN DSG CENTER - RECEP CAN KARAKAYA": "Ömer Kınalı",
  "SAMİ OTOMOTİV - SAMİ YILDIZ": "Seçkin Ozan Akıllı",
  "SANAL PARÇACI - ALİ AŞKUN": "Mustafa Koçalı",
  "SARICA OTO - BURHAN SARICA": "Ferhan Demir",
  "SAVAŞ OTOMOTİV-SAVAŞ SALTABAŞ": "Recep Yılmaz",
  "SAYRA GARAGE - HASAN BALLI": "Erbay Atlı",
  "SAĞLAM KARDEŞLER TEKSTİL TEM.MAD.OTOM.TAR.GIDA SAN.VE TİC.LTD.ŞTİ.": "Erbay Atlı",
  "SAĞLAM OTO YEDEK PARÇA - ABDÜLHAKİM OĞUL": "Alpaslan Değer",
  "SB İZCİ OTOMOTİV LTD.ŞTİ.": "Ferhan Demir",
  "SEB ALTINÇEKİÇ OTO SERVİS SANAYİ VE TİC.LTD.ŞTİ.": "Onur Selvi",
  "SEDAT OTO - SEDAT ZENGİN": "Alpaslan Değer",
  "SEKOM OTOMOTİV YED.PARÇ.NAK.TUR.EM.İNŞ.SAN.VE TİC.LTD.ŞTİ.": "Engin Alaca",
  "SELAHATTİN ÜSTÜN OTOM.YED.PAR.İNŞ.TEKS.SAN.VE TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "SELY GARAGE - EREN YORULMAZ": "Eren Aykut",
  "SELİM OTOMOTİV - SELAHATTİN SEZGİN": "Mustafa Koçalı",
  "SERDAR OTOMOTİV - MUSTAFA DEMİRKAN": "Onur Selvi",
  "SERHAD TİCARET - SERHAD KAZANCI": "Serdar Parlakkan",
  "SERHAT OTOMOTİV - SERHAT ERSOY": "Ferhan Demir",
  "SERKAN KILIÇ": "Serdar Parlakkan",
  "SERKAN OTO YEDEK PARÇA - SERKAN SÖKMEN": "Mustafa Koçalı",
  "SEVENKAR OTOMOTİV İTH. İHR.SAN VE TİC. LTD.ŞTİ": "Mustafa Koçalı",
  "SEVİMLİ OTOMOTİV ORJİNAL YEDEK PARÇA - VEYSİ KADAN": "Alpaslan Değer",
  "SEYREK OTOMOTIV - ÖMER SEYREK": "Engin Alaca",
  "SEZAŞ OTOMOTİV SAN. VE TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "SEZER OTO - İSMAİL SEZER": "Alpaslan Değer",
  "SEZER OTOMOTİV - NECMETTİN AKÇA": "Erbay Atlı",
  "SEÇ OTOMOTİV - MURAT HAZIRBULAN VE ORT.": "Seçkin Ozan Akıllı",
  "SEÇER OTO VOLKSWAGEN YEDEK PARÇA - CUMA SEÇER": "Serdar Parlakkan",
  "SEÇER OTO VOLKSWAGEN YEDEK PARÇA - CUMA SEÇER - ADANA": "Serdar Parlakkan",
  "SEÇER OTO VOLKSWAGEN YEDEK PARÇA - CUMA SEÇER - MEZİTLİ": "Serdar Parlakkan",
  "SEÇKİN OTOMOTİV OTO BAKIM ONARIM TİC. VE SAN.LTD.ŞTİ. / MERKEZ": "Engin Alaca",
  "SEÇKİN OTOMOTİV OTO BAKIM ONARIM TİC. VE SAN.LTD.ŞTİ./ BURSA": "Engin Alaca",
  "SHS ARAÇ KİRALAMA LOJ.VE OTO TİC.A.Ş.": "Recep Yılmaz",
  "SIDDIK OTO - OTO YEDEK PARÇA - CAFER VE ADEM YAZIBAĞLI ORT.": "Alpaslan Değer",
  "SILA OTO PARÇALARI SAN.VE TİC.LTD.ŞTİ.": "Erbay Atlı",
  "SINAR OTOMOTİV - UĞUR SINAR": "Seçkin Ozan Akıllı",
  "SINAR OTOMOTİV YEDEK PARÇA - ÖMER BAYRAKTAR SINAR": "Seçkin Ozan Akıllı",
  "SIRADAKİ PARÇA - ŞABAN ÇOŞKUN": "Engin Alaca",
  "SKAY OTOMOTİV A.Ş.": "Cüneyt Baş",
  "SKS MOTORS OTOMOTİV TİCARET VE SAN.LTD.ŞTİ.": "Ömer Kınalı",
  "SKY OTO YEDEK PARÇA - SELÇUK BERKTAŞ": "Serdar Parlakkan",
  "SKYL KALIP YEDEK PARÇA SAN. VE TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "SMART ELEKTRİKLİ ARAÇLAR SERVİS VE TİC.LTD.ŞTİ.": "Ferhan Demir",
  "SML DİZAYN - İSMAİL TEKİN": "Ferhan Demir",
  "SNC AUTO - RIDVAN ŞANCI": "Engin Alaca",
  "SODSAN STANDART OTO DÖŞEME SAN.TİC.A.Ş.": "Engin Alaca",
  "SOFULAR OTOMOTİV TARIM HAYVANCILIK SAN.VE TİC.LTD.ŞTİ.": "Erbay Atlı",
  "SON OTO YEDEK PARÇA - ASLI GÜL": "Mustafa Koçalı",
  "SPECTRA CONTA LTD.ŞTİ.": "Cüneyt Baş",
  "ST GARAGE -  SÜLEYMAN TALAYMANOĞLU": "Eren Aykut",
  "STANDART CONTA SANAYİ VE TİCARET LİMİTED ŞİRKETİ": "Cüneyt Baş",
  "STAR ÖZEL OPEL SERVİSİ - SİNAN FERHAT": "Erbay Atlı",
  "STİL OTO YEDEK PARÇA -  GÜRSEL YILMAZ": "Recep Yılmaz",
  "STİL OTOMOTİV - MEHMET BOZBAY": "Onur Selvi",
  "SUN TİCARET- ORHAN SUN": "Alpaslan Değer",
  "SUSUZ İNŞAAT SANAYİ VE TİCARET LTD.ŞTİ.": "Mustafa Koçalı",
  "SYM OTOMOTİV - AHMET KARAKOYUN": "Ferhan Demir",
  "SÖKE FİAT OTOM.YED.PAR. - VOLKAN AKSAY": "Sefa Akkan",
  "SÜLEYMAN GÜLKAR OTO ORİJİNAL YEDEK PARÇA - SÜLEYMAN KARA": "Serdar Parlakkan",
  "SÜLEYMAN OTO SKODA VOLKSWAGEN YED. PAR.- MERYEM KUBİLAY": "Recep Yılmaz",
  "SÜLEYMAN OTOMOTİV TİC.VE SAN.LTD.ŞTİ.": "Cüneyt Baş",
  "SÜNGER KARDEŞLER OTOMOTİV - ÇETİN SÜNGER": "Alpaslan Değer",
  "SÜRMELİ OTOMOTİV - EYYÜP KANLI": "Alpaslan Değer",
  "SİM SİM OTOMOTİV PETROL İNŞ. GIDA TUR. TİC.VE SAN.LTD.ŞTİ.": "Ömer Kınalı",
  "TAHA DURGUN": "Mustafa Koçalı",
  "TAKIM OTOMOTİV YED.PARÇ.İTH.İHR.SAN.TİC.LTD.ŞTİ.": "Seçkin Ozan Akıllı",
  "TAKIM OTOMOTİV YED.PARÇ.İTH.İHR.SAN.TİC.LTD.ŞTİ./ ŞUBE": "Seçkin Ozan Akıllı",
  "TAMPONCU HALİL - HALİL CAN GÜRBÜZ": "Eren Aykut",
  "TANER HORSANALI": "Ferhan Demir",
  "TANER HORSANALI / ŞUBE": "Ferhan Demir",
  "TARÇIN OTOMOTİV SAN.TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "TAŞCIOĞLU TİC. - VEDAT TAŞCIOĞLU": "Alpaslan Değer",
  "TAŞDELEN OTOMOTİV YED.PAR. - BURAK TAŞDELEN": "Alpaslan Değer",
  "TAŞIN OTO - OSMAN YAMAN": "Engin Alaca",
  "TAŞKANLAR OTO YEDEK PARÇA - MUSTAFA TAŞKAN": "Seçkin Ozan Akıllı",
  "TAŞLIK OTO RADYATÖR - ÖZKAN TAŞLIK": "Ali Osman Demir",
  "TAŞLIK OTO RADYATÖR TAMIR BAKIM VE EGZOS SISTEMLERI - ŞABAN TAŞLIK": "Ali Osman Demir",
  "TC OTOMOTİV YEDEK PARÇA - BELGİN UZUN": "Engin Alaca",
  "TEK RADYATÖR OTO YEDEK PARÇA ITHALAT IHRAAT SAN.TIC.LTD.ŞTI": "Ali Osman Demir",
  "TEKGÜL OTO YEDEK PARÇA - TEVFİK TEKGÜL": "Onur Selvi",
  "TEKPARÇA OTOMOTİV LTD.ŞTİ.": "Engin Alaca",
  "TEKTAŞ OTOMOTİV YED.PAR. - MUSTAFA OKUNAN": "Recep Yılmaz",
  "TEKİN UZUN": "Engin Alaca",
  "TEKİNALP TİCARET - MAHMUT TEKİNALP": "Cüneyt Baş",
  "TEMEL OTOMOTİV SAN.VE TİC.LTD.ŞTİ. / MASLAK": "Ferhan Demir",
  "TEMEL OTOMOTİV SAN.VE TİC.LTD.ŞTİ. / İKİTELLİ": "Mustafa Koçalı",
  "TEMİZ İŞ OTO RADYATÖR SAN. VE TİC. LTD.ŞTİ.": "Ali Osman Demir",
  "TENEKECİOĞLU OTOMOTİV YEDEK PARÇA İTH.İHR.TİC.LTD.ŞTİ.": "Serdar Parlakkan",
  "TEYO OTO-TEYMUR TATAR": "Mustafa Koçalı",
  "TEZ İŞ OTO RADYATÖR KLİMA VE YEDEK PARÇA - ORHAN ÖZCAN": "Ali Osman Demir",
  "TOKDEN OTO YEDEK PAÇÇA TURZ.İNŞ.TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "TOKGÖZ OTO YEDEK PARÇA BURAK TOKGÖZ": "Ömer Kınalı",
  "TOPAK OTOMOTİV YEDEK PARÇA - SÜLEYMAN TOPAK": "Serdar Parlakkan",
  "TOPALOĞLU OTOMOTİV İNŞAAT VE TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "TOPGÜL OTO YEDEK PARÇA MARKET SAN. TIC. PAZ. LTD. ŞTI.": "Alpaslan Değer",
  "TOSYA ÇAĞDAŞ OTOMOTİV SERVİS YEDEK PARÇA SANAYİ VE TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "TR ÖZTÜRKLER OTOMOTİV SERVİS HİZM.TUR.İNŞ.TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "TRABZON GARAGE - ZEYNEP BAYRAK BULUT": "Ömer Kınalı",
  "TRİGERMARKET OTOMOTİV SAN.TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "TUNA MOTORLU ARAÇLAR OTOMOTİV TUR.GIDA İNŞ.SAN.VE TİC.LTD.ŞTİ.": "Onur Selvi",
  "TUNA OTOMOTİV - MUSTAFA ŞAHİN": "Ömer Kınalı",
  "TUNA TİCARET - PERİHAN TUNA": "Eren Ateş",
  "TUNCER TEKNİK - FURKAN TUNCER": "Erbay Atlı",
  "TUNEM OTOMOTİV SANAYİ VE TİC.LTD.ŞTİ.": "Alpaslan Değer",
  "TUNÇ TİCARET ENDER USD": "Ferhan Demir",
  "TUNÇ YEDEK PARÇA OTOMOTİV A.Ş.": "Recep Yılmaz",
  "TURAN OTO RADYATÖR VE YEDEK PARÇA - RAZİYE ÖZKAN": "Ali Osman Demir",
  "TURAN OTOMOTİV YED.PAR. - ÖMER TURAN": "Seçkin Ozan Akıllı",
  "TURAN YEDEK PARÇA OTOMOTİV İTHALAT İHRACAT SAN. VE TİC.LTD.ŞTİ.": "Erbay Atlı",
  "TURGUTLAR AUTO VE YED.PAR. - YAVUZ TURGUT": "Erbay Atlı",
  "TURHAN OTO İÇ VE DIŞ TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "TURHAN OTOMOTİV - TURHAN BALCIOĞLU": "Ferhan Demir",
  "TURHAN TİCARET - HÜSEYİN TURHAN ORT.": "Mustafa Koçalı",
  "TURKOCAR MOTORLU ARAÇLAR SAN.VE TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "TURKZEN YAZILIM DANIŞMANLIK OTOMOTİV HİZMETLERİ - AHMET SAMET AKDAĞ": "Recep Yılmaz",
  "TURUNÇ OTOMOTİV EMLAK TURİZM TAŞ.VE TİC. LTD.ŞTİ.": "Cüneyt Baş",
  "TUTKU OTO YEDEK PARÇA SAN.VE TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "TUĞLU METİN OTOMOTİV - METİN ÖZEL": "Onur Selvi",
  "TÜMPAR OTOMOTİV İTH.İHR.SAN. VE TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "TÜRKER OTO PARÇALARI TİCARET LİMİTED ŞİRKETİ": "Recep Yılmaz",
  "TÜRKYILMAZ MOT.AR.NAK.TUR.İNŞ.İTH.İHR.SAN VE TİC.LTD.ŞTİ - MERKEZ": "Eren Ateş",
  "TÜRKYILMAZ MOT.AR.NAK.TUR.İNŞ.İTH.İHR.SAN VE TİC.LTD.ŞTİ - İSKİTLER": "Eren Ateş",
  "TÜRKYILMAZ MOT.AR.NAK.TUR.İNŞ.İTH.İHR.SAN VE TİC.LTD.ŞTİ - İVEDİK": "Eren Ateş",
  "TÜRKZEN TEKNİK - MEHMET BAY": "Recep Yılmaz",
  "TÜRKÖZ YEDEK PARÇA - RAİF CAN TÜRKÖZ": "Ömer Kınalı",
  "TİTİZ OTO RADYATÖR - UĞUR ÖZKAN": "Ali Osman Demir",
  "TİTİZ RADYATÖR DEPO KALORİFER TAMİR BAKIM - FADİME DOĞDU": "Ali Osman Demir",
  "UFUK OTOMOTİV - VEYSEL YUSUF BALI": "Alpaslan Değer",
  "ULAŞ GRUP TURİZM OTOMOTİV TİCARET VE PAZ.LTD.ŞTİ.": "Onur Selvi",
  "ULAŞ GRUP TURİZM OTOMOTİV TİCARET VE PAZ.LTD.ŞTİ. / TOPTAN": "Cüneyt Baş",
  "ULAŞ GRUP TURİZM OTOMOTİV TİCARET VE PAZ.LTD.ŞTİ./ ŞUBE": "Onur Selvi",
  "ULTRA GRUP ORJ.ÇIK.YED.PAR.- ALİ ÇETİN": "Recep Yılmaz",
  "ULU OTO RADYATÖR - HACI ULUKÜTÜK": "Ali Osman Demir",
  "ULUSAL OTOMOTİV YEDEK PARÇA - İBRAHİM ULUSAL": "Serdar Parlakkan",
  "ULUĞSOY OTOM.ULUSLARARASI NAK.TAŞ.İNŞT.TARIM SAN.TİC.LTD.ŞTİ.": "Ali Osman Demir",
  "UMT GARAGE UMUT OTO YEDEK PARÇA ELEKT.VE AKS.SAN.TİC.LTD.ŞTİ.": "Ferhan Demir",
  "UMUT OTO YEDEK PARÇA - HALİL KALKAN VE DURMUŞ GENCTÜRK": "Serdar Parlakkan",
  "UMUT OTOMOTİV TİC.LTD.ŞTİ.": "Alpaslan Değer",
  "UNİRELL YED.PARÇ.PAZ.SAN.VE TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "URGENT AUTO -  METİN BERK ALTUNAY": "Seçkin Ozan Akıllı",
  "USTA OTOMOTİV - MEHMET BOZKURT": "Seçkin Ozan Akıllı",
  "UYAR RADYATÖR OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Ali Osman Demir",
  "UYGUN OTO YEDEK PARÇA - GÖKHAN MANDACIOĞLU": "Cüneyt Baş",
  "UYGUN TEKSTİL OTOMOTİV SAN.VE TİC.LTD.ŞTİ./ ŞUBE": "Ferhan Demir",
  "UYGUN TEKSTİL OTOMOTİV SANAYİ VE TİC.LTD.ŞTİ.": "Ferhan Demir",
  "UZAY OTO RADYATÖR VE KALORİFER SERVİSİ - RAMAZAN TÜREGÜN": "Ali Osman Demir",
  "UZLAR İSTANBUL OTOMOTİV VE İNŞAAT SANAYİ TİCARET LTD.ŞTİ": "Ferhan Demir",
  "UZN GÖKTÜRK GRUP - ZEYTUN SEMİH KARACA": "Recep Yılmaz",
  "UZN OTOMOTİV - MEVLÜT UZUN": "Erbay Atlı",
  "UZUN OTOMOTİV - MEHMET UZUN": "Recep Yılmaz",
  "UZUNKILIÇ OTOMOTİV YED.PAR.İNŞ.GID.SAN.VE TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "UÇAR YEDEK PARÇA - BURAK UÇAR": "Recep Yılmaz",
  "V.A.G OTOMOTİV YEDEK PARÇA ALİ ELİUZ": "Sefa Akkan",
  "VACAR GARAJ - NAZLICAN EBRAR TOPALLAR": "Eren Aykut",
  "VAG ELEKTRONİK - EMRE SARAÇOĞLU": "Eren Aykut",
  "VAG GARAGE TUNING / ŞUBE": "Eren Aykut",
  "VAG MOTORLU TAŞITLAR YED.PARÇ.İML.İTH.İHR.SAN.VE TİC.LTD.ŞTİ.": "Serdar Parlakkan",
  "VAG OTOMOTİV SAN.VE TİC.A.Ş.": "Seçkin Ozan Akıllı",
  "VAG PREMIUNN SERVİS - TALHA MENTEŞ": "Engin Alaca",
  "VAG PRO OTOMOTİV ORJ.YAN SAN.YED.PAR. - TURAN TEKİN": "Alpaslan Değer",
  "VAG-ER OTO YEDEK PARÇA - EREN BOZ": "Recep Yılmaz",
  "VAG-PARTS OTO YED.PAR. - EMRULLAH AKGÖL": "Ferhan Demir",
  "VAG-PARTS OTO YEDEK PARÇA - MUHAMMET SAMİ AKGÖL": "Ferhan Demir",
  "VAGENPAR OTOMOTIV YEDEK PARÇA SAN.VE TIC.LTD.ŞTI.": "Engin Alaca",
  "VAGPAR OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Eren Ateş",
  "VASS GROUP OTOMOTİV SANAYİ VE TİC.LTD.ŞTİ.": "Serdar Parlakkan",
  "VASSCAR AUTO - AYŞEGÜL YÜKSEL & SERCAN ŞENEL ADİ ORT.": "Ömer Kınalı",
  "VASSPAR OTOMOTİV YEDEK PAR.SAN.VE TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "VAV AUTO OTOMOTİV YEDEK PARÇA SERV.TAŞ.İNŞ.SAN.VE TİC.LTD.ŞTİ.": "Alpaslan Değer",
  "VEYSEL OTOMOTİV ORJİNAL YEDEK PARÇA - VEYSEL ÖZTOPRAK": "Serdar Parlakkan",
  "VM GRUP OTOMOTİV SAN.VE TİC.A.Ş.": "Eren Ateş",
  "VOLKAN OTOMOTİV İTH.VE TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "VOLKSWAGEN ÇIKMA YEDEK PARÇA - YASİN ŞEN": "Seçkin Ozan Akıllı",
  "VOLKSWAGENCİ AHMET ERCAN MİLYON": "Engin Alaca",
  "VOLKSWAGENCİM ÖZEL SERVİS YEDEK PARÇA - ZAFER KORKUT": "Onur Selvi",
  "VOPAR OTOMOTİV İNŞ.SAN.VE TİC.LTD.ŞTİ.": "Seçkin Ozan Akıllı",
  "VOS OTO YEDEK PARÇA - HAKAN GENÇ": "Eren Ateş",
  "VOSCAR OTOMOTİV - MURAT KAYMAZ VE ORTAĞI": "Ferhan Demir",
  "VOSCENTER OTO YEDEK PARÇA - SONER ÇORUMLU": "Sefa Akkan",
  "VOSMAR OTO YEDEK PARÇA - MUHAMMED ÇELİK": "Alpaslan Değer",
  "VOSPAR OTOMOTİV - AHMET PASLIOĞLU": "Seçkin Ozan Akıllı",
  "VOSPAR OTOMOTİV - MEHMET PASLIOĞLU": "Seçkin Ozan Akıllı",
  "VOSSAN OTOMOTİV LTD.ŞTİ.": "Erbay Atlı",
  "VOSVOS OTOMOTİV - YASİN EKİNCİ": "Engin Alaca",
  "VOSVOS OTOMOTİV İTH.İHR.SAN.TİC.A.Ş.": "Mustafa Koçalı",
  "VOSVOS TİCARET OSMAN DEMİR VE ORTAĞI": "Mustafa Koçalı",
  "VOSWOS OTOMOTİV - CELAL ÇEKEREKLİ": "Ferhan Demir",
  "VS OTOMOTİV - SALİH SEVGİCAN": "Erbay Atlı",
  "VTS KÖRÜK - AZİZ KATIRCI": "Engin Alaca",
  "VW ERTAN MOTORLU ARAÇLAR SAN TİC LTD.ŞTİ": "Onur Selvi",
  "VİZYON AUTO PARTS ORİJİNAL YEDEK PARÇALARI - İBRAHİM İSKENDERUN": "Serdar Parlakkan",
  "VİZYON OTO - MURAT TARHAN": "Mustafa Koçalı",
  "VİZYON RULMAN - ÇAĞRI KILINÇARSLAN": "Eren Ateş",
  "VİZYON İKİNCİ EL YEDEK PARÇA OTOMOTİV TİC. LTD. ŞTİ.": "Eren Ateş",
  "WAG PARTS OTOMOTİV SANAYİ İNŞAAT VE DIŞ TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "WAGEN OTOMOTİV YED.PAR. DIŞ. TİC. SAN. VE TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "WASSCAR OTOMOTİV - SAMET KAYNAR": "Ömer Kınalı",
  "WASSPAR OTOMOTİV İNS.SAN.TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "WOPEL MOTORLU ARAÇLAR - SİNAN CANDAN": "Seçkin Ozan Akıllı",
  "WOS-MER OTO YEDEK PARÇA - ADEM YILMAZ": "Ömer Kınalı",
  "WOS-PAR YED.PAR. - ÖMER FARUK ÇELİKKAYA": "Onur Okumuş",
  "WOSPARTS OTOMOTİV - ALEYNA HACITEMELOĞLU": "Mustafa Koçalı",
  "WOSPEL OTOMOTİV - MUHAMMED NAVRUZ / ZEYTİNBURNU": "Ferhan Demir",
  "WOSS OTOMOTİV - HÜSEYİN TATLI": "Serdar Parlakkan",
  "WOSSMER OTO YED.PARÇ.VE AKS.OTO.SAN.TİC.LTD.ŞTİ.": "Alpaslan Değer",
  "WOSTEK OTOMOTİV - İRFAN ÖZDRMİR- EMRAH ÇAKIRSOY- OSMAN GÖKOĞLU-  FATİH ÖZBEY": "Ömer Kınalı",
  "WOSTİME YEDEK PARÇA - İSMAİL DEMİR": "Eren Ateş",
  "WOSWOS OTOMOTİV - ASLAN TARKAN ÇEPNİ": "Ömer Kınalı",
  "Y.T.T. OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "YAKIN OTOMOTİV - ERDİNÇ YAKIN": "Onur Selvi",
  "YALÇIN GÜÇLÜOĞLU": "Cüneyt Baş",
  "YALÇIN OTO RADYATÖR - YAŞAR YALÇIN TEPECİ": "Ali Osman Demir",
  "YAMAK TİCARET - BEYTULLAH YAMAK": "Recep Yılmaz",
  "YAMANLAR TAŞIT YEDEK PARÇA SANAYİ VE TİC. LTD.ŞTİ": "Engin Alaca",
  "YARDİBİ OTOMOTİV - VURAL YARDİBİ": "Ömer Kınalı",
  "YAVUZ OTO YEDEK PARÇA - YAVUZ SELİM KOYUNCU": "Ferhan Demir",
  "YAVUZLAR OTO YED.PAR. - TAHSİN MELİHCAN YAVUZ": "Onur Okumuş",
  "YAVUZSTAR OTOMOTİV İNŞAAT TURİZM SAN. VE TİC. LTD. ŞTİ.": "Mustafa Koçalı",
  "YAYIL OTOMOTİV SERVİS YEDEK PARÇA - HALİL YAYIL": "Engin Alaca",
  "YAZICI OTOMOTİV - ENES EREN": "Mustafa Koçalı",
  "YAĞIZ VAG GARAGE - HASAN ALİ KARAKUŞ": "Eren Aykut",
  "YAĞMUR OTO TAM.VE BAK.SER. - ÖMER BATUR": "Seçkin Ozan Akıllı",
  "YAŞAR OTOMOTİV VE YED. PARÇA TİC. - YAŞAR URHAN": "Recep Yılmaz",
  "YAŞAR OTOMOTİV YEDEK PARÇA - ÖMER YAŞAR": "Alpaslan Değer",
  "YAŞAR SELVİ OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Engin Alaca",
  "YCL KAR OTOMOTİV VE YEDEK PARÇA TİC.LTD.ŞTİ.": "Serdar Parlakkan",
  "YDS DANIŞMANLIK OTOMOTİV SANAYİ VE TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "YEDEK PARK OTO YEDEK PARÇA - ŞEHMUS TUNÇ": "Alpaslan Değer",
  "YEDEKCO OTOMOTİV SANAYİ TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "YENİBAHAR OTO YED.PAR.TUR.PERS.VE ÖĞR.TAŞ.SAN.TİC.LTD.ŞTİ.": "Ali Osman Demir",
  "YESPAR OTO YEDEK PARÇA SAN.VE TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "YEĞENOĞLU OTO - İBRAHİM YEĞENOĞLU": "Eren Ateş",
  "YEŞİL KARDEŞLER RADYATÖR OTO.GIDA.İTH.İHR.SAN.VE TİC.LTD.ŞTİ.": "Ali Osman Demir",
  "YEŞİL OTOMOTİV - İBRAHİM HALİL BUNAT / ŞUBE": "Cüneyt Baş",
  "YGT OTO YEDEK PARÇA SAN.TİC.LTD.ŞTİ.": "Onur Selvi",
  "YILBAŞI OTO SERVİS HİZMETLERİ SAN.VE TİC.LTD.ŞTİ.": "Engin Alaca",
  "YILDIRIM GARAGE - AHMET YILDIRIM": "Eren Ateş",
  "YILDIRIM MOTORLU ARAÇLAR -AHMET YILDIRIM": "Eren Ateş",
  "YILDIRIM ORJ.VE İTH.YED.PARÇ.AKS.TOP.PAR. - NİZAMETTİN YILDIRIM": "Recep Yılmaz",
  "YILDIRIM OTO YEDEK PARÇA FATİH - ALİ YILDIRIM ORT.": "Engin Alaca",
  "YILDIRIM OTOMOTİV YEDEK PARÇA-YILDIRIM AKYÜZ": "Recep Yılmaz",
  "YILDIRIM YP OTOMOTİV YED.PAR.SAN.TİC.LTD.ŞTİ.": "Alpaslan Değer",
  "YILDIZ OTOMOTİV TURİZM - OSMAN YILDIZ": "Recep Yılmaz",
  "YILDIZ OTOMOTİV YEDEK PARÇA PARÇA TOPTAN PERAKENDE HAKAN PAÇACIOĞLU": "Sefa Akkan",
  "YILDIZ OTOMOTİV İLKER YILDIZ VE ORTAĞI": "Ferhan Demir",
  "YILDIZLAR OTOMOTİV YED.PAR.İTH.TİC.LTD.ŞTİ.": "Ferhan Demir",
  "YILMAZ OTOMOTİV - YILMAZ YURTSEVER": "Eren Ateş",
  "YILMAZLAR OTOMOTİV - SADÜL DOĞAN": "Engin Alaca",
  "YKS OTOMOTİV - MUHAMMED ENİS ÇİÇEK": "Cüneyt Baş",
  "YLDZ OTO İNŞAAT GIDA TEKSTİL SAN.VE TİC.LTD.ŞTİ.": "Ferhan Demir",
  "YOK YOK OTOMOTİV - ALİ ARI": "Alpaslan Değer",
  "YOLDAŞ TİCARET - BAHRİ YOLDAŞ": "Seçkin Ozan Akıllı",
  "YUR OTO YEDEK PARÇA - ÖMER FARUK YÜREK": "Eren Aykut",
  "YUSUF OTO YED.PRÇ.-YUSUF POLAT": "Alpaslan Değer",
  "YUSUF PEKEL - HYM TUNNİG": "Eren Aykut",
  "YUSUFOĞULLARI OTO - YUSUF TANIRGAN": "Seçkin Ozan Akıllı",
  "YÖRÜKOĞLU OTOMOTİV NAKLİYAT -  HÜSEYİN KOCAGÖBEK": "Sefa Akkan",
  "YÜCEL PAR - ABDULLAH YÜCEL": "Ferhan Demir",
  "YÜCELEN MOTORLU ARAÇLAR - ÖMER YURTOĞLU": "Eren Ateş",
  "YÜKSEL NAKİL VASITALARI OTO YEDEK PARÇA İNŞAAT SAN.TİC.LTD.ŞTİ.": "Sefa Akkan",
  "YÜKSEL OTO SANAYİ VE SERVİS HİZMETLERİ PAZ.LTD.ŞTİ.": "Ömer Kınalı",
  "YÜKSEL OTOMOTİV TOPTAN OTO YEDEK PARÇA - AYTAÇ OKUR": "Cüneyt Baş",
  "YÜKSEL PARTS OTOMOTİV YED.PAR.İNŞ.SAN.VE TİC.LTD.ŞTİ.": "Alpaslan Değer",
  "YİRİKOĞULLARI OTOMOTİV KONF.DERİ.SAN.VE.TİC.LTD.ŞTİ.": "Engin Alaca",
  "YİĞİT MOTOR - DAMLA YEŞİL": "Ömer Kınalı",
  "YİĞİT OTO PARÇA DÜNYASI - TANER YİĞİT": "Sefa Akkan",
  "YİĞİT OTOMOTİV HAKKI ÇAKMAKÇI -Z.SİLLELİ ORT": "Onur Selvi",
  "ZAFER OTOMOTİV ORM.ÜRN.NAK.KON KAV.İNŞ.TAAH.İML.İTH.İHR.SAN.VE TİC.LTD.ŞTİ.": "Eren Ateş",
  "ZAMAN OTOMOTİV VE YEDEK PARÇA - DOĞAN OKALİN": "Alpaslan Değer",
  "ZEKİ OTOMOTİV - COŞKUN BÜLBÜL": "Ferhan Demir",
  "ZEKİ OTOMOTİV - KEREM BÜLBÜL": "Ferhan Demir",
  "ZEKİ OTOMOTİV YEDEK PARÇA - UFUK KANDEMİR": "Ferhan Demir",
  "ZENGİNLER OTO YEDEK PARÇA - İLHAN ZENGİN": "Sefa Akkan",
  "ZEUGMA OTO YEDEK PARÇA - ABDULKADİR DEMİR": "Alpaslan Değer",
  "ZSG OTOMOTİV İTHALAT İHRACAT TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "ZİRVE OTO - ERAY KOR ( BAŞKENT SANAYİ)": "Eren Ateş",
  "ZİRVE OTOMOTİV - RECEP AYDIN": "Erbay Atlı",
  "ZİRVE POMPA - CELALETTİN ALINAK": "Erbay Atlı",
  "ZİRVE YEDEK PARÇA - HALİL BURDUR": "Onur Selvi",
  "ÇAKIR OTO - MEHMET ÇAKIR": "Ömer Kınalı",
  "ÇAKIR RADYATÖR - CEM ÇAKIR": "Ali Osman Demir",
  "ÇAKIR TİCARET - HÜSEYİN ÇAKIR": "Engin Alaca",
  "ÇAKMAK OTO RADYATÖR - YİĞİT YILDIRIM ERBAY": "Ali Osman Demir",
  "ÇAKMAK OTOMOTİV ORJ.L VE ITHAL YED. PARÇALARI - MUSTAFA ÇAKMAKLI": "Alpaslan Değer",
  "ÇALIŞIR GRUP OTO YEDEK PARÇA VE İNŞAAT TİCARET  LTD.ŞTİ. / ŞUBE": "Recep Yılmaz",
  "ÇALIŞIR GRUP OTO YEDEK PARÇA VE İNŞAAT TİCARET LTD.ŞTİ": "Recep Yılmaz",
  "ÇARTIL OTOMOTİV SANAYİ VE TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "ÇAĞ OTO PARTS YEDEK PARÇA - GÜNAY ALAN": "Engin Alaca",
  "ÇAĞLAR OTOMOTİV - ÇAĞLAR CÖMERT": "Serdar Parlakkan",
  "ÇAĞRI OTOMOTİV - EMİRHAN ERTÜRK": "Ferhan Demir",
  "ÇAĞRI OTOMOTİV SERV.YED.PAR. - FİKRET ATEŞ": "Onur Selvi",
  "ÇAĞRI SKODA YEDEK PARÇA SERVİS - İSMAİL BARBAROS & FUNDA ERDOĞAN ORT.": "Onur Selvi",
  "ÇELİK GRUP RULMAN SANAYİ VE TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "ÇELİK YEDEK PARÇA LTD.ŞTİ.": "Ali Osman Demir",
  "ÇELİKMAN OTOMOTİV YEDEK PARÇA TİC.LTD.ŞTİ.": "Erbay Atlı",
  "ÇERKEZOĞLU OTOMOTİV - MAHMUT YAPAR": "Seçkin Ozan Akıllı",
  "ÇEVİK OTOMOTİV - CENGİZ ÇEVİK": "Ali Osman Demir",
  "ÇEVİK OTOMOTİV - MUSTAFA ÇEVİK": "Ali Osman Demir",
  "ÇEVİK OTOMOTİV ARAÇ VE GEREÇLERİ İNŞ. TUR. SAN. VE TİC. LTD. ŞTİ. / ŞUBE": "Recep Yılmaz",
  "ÇEVİK OTOMOTİV ARAÇ VE GEREÇLERİ İNŞ.TUR.SAN.VE TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "ÇEVİK OTOMOTİV ORJİNAL YEDEK PARÇALARI - İBRAHİM HALİL ÇEVİK": "Cüneyt Baş",
  "ÇEVİK İNŞAAT ELEKTRİK ELEKTRONİK GIDA HAY.TUR.SAN.TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "ÇIRAK DİZAYN OTOMOTİV LTD.ŞTİ.": "Eren Aykut",
  "ÇOKPINAR OTO KLİMA OTOMOTİV İTH.İHR.SAN.VE TİC.LTD.ŞTİ.": "Ali Osman Demir",
  "ÇORUM AS OTOMOTİV YEDEK PARÇA SAN.VE TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "ÇORUM YGT GRUP OTMOTİV SAN.TİC.LTD.ŞTİ": "Ömer Kınalı",
  "ÇOŞAR OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Eren Ateş",
  "ÇUKUROVA OTO RADYATÖR VE YEDEK PARÇA - İBRAHİM ESİN": "Ali Osman Demir",
  "ÇİÇEKLER OTO RADYATÖR KLİMA YEDEK PARÇA İMALAT SANAYİ - MUHARREM ÇİÇEK": "Ali Osman Demir",
  "ÖDEMİŞ OTO YEDEK PARÇA - ÜMİT ÖDEMİŞ": "Onur Selvi",
  "ÖLMEZ OTO RADYATÖR - ERCAN ÖLMEZ": "Ali Osman Demir",
  "ÖMER ŞAHİN OTOMOTİV SAN. VE DIŞ TİC. A.Ş": "Ferhan Demir",
  "ÖMÜR OTO - SEMİH ÖMÜR": "Serdar Parlakkan",
  "ÖNAY YEDEK PARÇA OTOMOTİV İNŞ. TUR. SAN. VE TİC. LTD ŞTİ": "Ferhan Demir",
  "ÖNDER OTO SANAYİ VE TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "ÖNDER OTOMOTİV - YUSUF POLAT": "Alpaslan Değer",
  "ÖNEM TİCARET - ERSAN ÖNEM": "Alpaslan Değer",
  "ÖNERLER OTOMOTİV SAN VE TİC.LTD.ŞTİ": "Ferhan Demir",
  "ÖRÜKÇÜLOĞLU MOT.ARAÇ.YED.PARÇA MADENİ YAĞ NAKLİYE İNŞ.TEKSTİL LTD ŞTİ": "Seçkin Ozan Akıllı",
  "ÖZ DİCLE OTOMOTİV İNŞAAT GIDA TEKSTİL SANAYİ VE TİCARET LİMİTED ŞİRKETİ": "Alpaslan Değer",
  "ÖZ KOÇ RADYATÖR - BEDİR AVCİ": "Alpaslan Değer",
  "ÖZ OPEL OTOMOTİV - SİNAN ABAYLI": "Engin Alaca",
  "ÖZ İLERİ OTO YEDEK PAR.PETR.İNŞ.MAK.TAR.İTH.İHR.SAN.VE TİC.LTD.ŞTİ.": "Alpaslan Değer",
  "ÖZ İLKAYALAR OTO INŞ TARIM VE PET. ÜR.SAN İÇ VE DIŞ TİC. LTD. ŞTİ.": "Erbay Atlı",
  "ÖZ-ER OTOMOTİV ÖMER ER VE BATUHAN ER ORTAKLIĞI": "Seçkin Ozan Akıllı",
  "ÖZ-NUR OTO FATİH": "Ferhan Demir",
  "ÖZAY TURAN": "Ferhan Demir",
  "ÖZBAY OTOMOTİV YEDEK PAR. - MEHMET ASIM ÖZBAY": "Alpaslan Değer",
  "ÖZBEK OTOMOTİV - YİĞİT ATİLLA ÖZBEK": "Ferhan Demir",
  "ÖZBEY OTOMOTİV - SEDA MERCAN": "Alpaslan Değer",
  "ÖZBİR OTO YEDEK PARÇA AKSESUAR BOYA SATIŞ VE UYG. MARK. - BİROL ÖZTÜRK": "Engin Alaca",
  "ÖZCAN CEYLAN OTO YEDEKPARÇA OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Sefa Akkan",
  "ÖZCAN OTO - HÜSEYİN ÖZCAN": "Engin Alaca",
  "ÖZCAN TİCARET - RECEP ÖZCAN": "Erbay Atlı",
  "ÖZCANLAR MAD.YAĞ OTO YED.PAR. - ALİ ÖZCAN": "Onur Selvi",
  "ÖZCANLAR YEDEK PARÇA OTOM.İNŞ.İTH.İHR.SAN.VE TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "ÖZCANLI OTO YEDEK PARÇA - ÖMER ÖZCANLI": "Engin Alaca",
  "ÖZCENGİZLER OTOMOTİV - RECEP CENGİZ": "Mustafa Koçalı",
  "ÖZDEM MOTORLU ARAÇLAR YEDEK PARÇA TİC.LTD.ŞTİ.": "Ferhan Demir",
  "ÖZDEMİR OTO JAPON VE ALMAN YEDEK PARÇALARI - FUAT ÖZDEMİR": "Cüneyt Baş",
  "ÖZDOĞAN OTOMOTİV YEDEK PARÇA - İBRAHİM DOĞAN": "Serdar Parlakkan",
  "ÖZEN YEDEKPARÇA OTOM.AKARY.İNŞ.SAN.VE TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "ÖZENİR RADYATÖR - İNTERCOLLER BAKIM SERVİSİ - BAYRAM ÖZCAN": "Ali Osman Demir",
  "ÖZGE ÖZDEMİR CENGİZ": "Serdar Parlakkan",
  "ÖZGÜR OTO - TAHİR DEMİR": "Alpaslan Değer",
  "ÖZHATİPOĞLU TİCARET MERKEZ - NİZAMİ ALTINEL": "Engin Alaca",
  "ÖZHATİPOĞLU TİCARET MERKEZ - NİZAMİ ALTINEL / ŞUBE": "Engin Alaca",
  "ÖZHATİPOĞLU TİCARET MERKEZ - NİZAMİ ALTINEL / ŞUBE 2": "Engin Alaca",
  "ÖZKA OTOMOTİV-MÜSLÜM ÖZKAN": "Serdar Parlakkan",
  "ÖZKAN OTO YEDEK PARÇA SANAYİ VE TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "ÖZKAN OTOMOTİV - FERDİ ÖZKAN": "Serdar Parlakkan",
  "ÖZKAN OTOMOTİV YEDEK PARÇA - ÖZKAN DİKMEN": "Seçkin Ozan Akıllı",
  "ÖZKANLAR OTO YEDEK PARÇA - AHMET ÖZKAN KARABULUT": "Engin Alaca",
  "ÖZKAR OTOMOTİV - CİHAN KARACA": "Ömer Kınalı",
  "ÖZKARİST OTOMOTİV İNŞAAT TUR.SAN.VE TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "ÖZKAYALAR OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "ÖZKESERLER TİC. - SEFA KESER": "Erbay Atlı",
  "ÖZKONYA OPEL SERVİSİ-CENGİZ FİL OTOMOTİV TAR. VE HAY.PAZ.SAN.LTD.ŞTİ.": "Erbay Atlı",
  "ÖZKOÇ OTOMOTİV - YAKUP KOÇ": "Erbay Atlı",
  "ÖZKÜÇÜK OTO YEDEK PARÇA - MUSTAFA ÖZKÜÇÜK": "Ömer Kınalı",
  "ÖZLEM GRUP OTO.MAK.İNŞT.HIRD.GIDA TRZM.İTH.İHRCT.SAN. VE TİC.LTD.ŞTİ.": "Eren Ateş",
  "ÖZMAŞA OTOMOTİV OTO YEDEK PARÇA EMİNE MAŞA SAKİN MAŞA ORT.": "Serdar Parlakkan",
  "ÖZMEN OTOMOTİV İNŞ. GID.TEMZ.AC.NAKL.GİYİM.İML.TAMİR SAN.VE TİC.LTD.ŞTİ.": "Eren Ateş",
  "ÖZMER MERCEDES ORJ.YENİ ÇIK.OTO YED.PAR. - ÖZER DEVECİ": "Serdar Parlakkan",
  "ÖZMER OTO - MEHMET EMİN KIRAN": "Ömer Kınalı",
  "ÖZOTO ŞARK RADYATÖR SAN.VE TİC.LTD.ŞTİ.": "Ali Osman Demir",
  "ÖZPINAR RADYATÖR - SELMA ÖZPINAR": "Ali Osman Demir",
  "ÖZTEKGÜL İNŞAAT A.Ş.": "Onur Selvi",
  "ÖZTOPRAK OTOMOTİV OTO YEDEK PARÇA - ŞERAFETTİN ÖZTOPRAK": "Alpaslan Değer",
  "ÖZTÜRK OTO SERVİS YEDEK PARÇA SANAYİ VE TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "ÖZYURT OPEL CHEVR.ORJ.YED.PAR.VE AKS. - ZAFER AYDOĞDU": "Serdar Parlakkan",
  "ÖZÇELİK OPEL VE CHEVROLET YEDEK PARÇA - BEKİR ÖZÇELİK": "Eren Ateş",
  "ÖZÇELİKLER OTOM.İNŞ.TUR.PAZ.SAN.VE TİC.LTD.ŞTİ. / BAŞKENT": "Eren Ateş",
  "ÖZÇELİKLER OTOM.İNŞ.TUR.PAZ.SAN.VE TİC.LTD.ŞTİ. / PERAKENDE": "Eren Ateş",
  "ÖZÇELİKLER OTOM.İNŞ.TUR.PAZ.SAN.VE TİC.LTD.ŞTİ./ ŞAŞMAZ": "Eren Ateş",
  "ÜMİT MUHAMMET SAĞDIÇ KADİR ERKAN ADİ ORT.": "Ömer Kınalı",
  "ÜMİT ÖZKAN OTO.İTH.İHR.SAN.VE.TİC.LTD.ŞTİ.": "Seçkin Ozan Akıllı",
  "ÜNAL TİCARET - YELİZ ÇAYHAN ÜRGENÇ": "Serdar Parlakkan",
  "ÜNGÖR OTO YEDEK PARÇA -  ELİF ATAKAN": "Recep Yılmaz",
  "ÜNLÜ OTO LTD.ŞTİ.": "Eren Ateş",
  "ÜNSAL OTOMOTİV - RECEP ÜNSAL": "Ferhan Demir",
  "ÜSTÜN OTOMOTİV - HASAN HÜSEYİN ZORKAYA": "Alpaslan Değer",
  "ÜÇBEY YEDEK PARÇA ARİF BÜYÜKÖZ-HÜSEYİN ŞAHİN VE HÜSEYİN AYAN ADİ ORTAKLIĞI": "Seçkin Ozan Akıllı",
  "ÜÇBİRLİK MOTORLU ARAÇLAR YEDEK PARÇA SERVİS HİZ.TİC.LTD.ŞTİ.": "Sefa Akkan",
  "ÜÇEL OTOMOTİV SAN.VE TİC.A.Ş. - ANKARA": "Cüneyt Baş",
  "ÜÇEL OTOMOTİV SAN.VE TİC.A.Ş. - BOSTANCI": "Recep Yılmaz",
  "ÜÇEL OTOMOTİV SAN.VE TİC.A.Ş. - BURSA": "Engin Alaca",
  "ÜÇEL OTOMOTİV SAN.VE TİC.A.Ş. - KAYSERİ": "Seçkin Ozan Akıllı",
  "ÜÇEL OTOMOTİV SAN.VE TİC.A.Ş. - MERKEZ": "Cüneyt Baş",
  "ÜÇEL OTOMOTİV SAN.VE TİC.A.Ş. - SAMSUN": "Ömer Kınalı",
  "ÜÇEL OTOMOTİV SAN.VE TİC.A.Ş. - TOPTAN": "Recep Yılmaz",
  "ÜÇEL OTOMOTİV SAN.VE TİC.A.Ş. - İKİTELLİ": "Mustafa Koçalı",
  "ÜÇEL RULMAN TİCARET - YAKUP ZEDELENMEZ VE ORT.": "Erbay Atlı",
  "ÜÇEL1 OTOMOTİV SANAYİ VE TİC LTD.ŞTİ.": "Ferhan Demir",
  "ÜÇLER OTOMOTIV OTO YEDEK PARÇA - İSMAİL EMRE HALAÇ": "Recep Yılmaz",
  "ÜÇLER OTOMOTİV EFRAHİM KAMBEROĞLU VE ORTAKLARI": "Mustafa Koçalı",
  "İBRAHİM TAÇ": "Ferhan Demir",
  "İBRAHİM TURUNÇ": "Serdar Parlakkan",
  "İBRAHİM ÜZÜMBAĞI": "Serdar Parlakkan",
  "İDEAL OTO YEDEK PARÇA - HASAN AĞAR": "Engin Alaca",
  "İDEAL OTOMOTİV OTO YEDEK PARÇA - YUNUS YAVUZ / ŞUBE": "Engin Alaca",
  "İDEAL OTOMOTİV OTO YEDEK PARÇA-YUNUS YAVUZ": "Engin Alaca",
  "İDEAL OTOMOTİV OTO YEDEK PARÇA-İBRAHİM TÖRÜN": "Engin Alaca",
  "İHVANLAR OTO KAPORTA BOYA İNŞT.TAAH.SAN.TİC.LTD.ŞTİ.": "Recep Yılmaz",
  "İKLİM OTOMOTİV -MUSTAFA ÇİL": "Ali Osman Demir",
  "İKİLER EFE OTOMOTİV SANAYİ VE TİCARET LTD.ŞTİ.": "Cüneyt Baş",
  "İKİLER OTO YEDEK PARÇA - RECEP IŞIK": "Engin Alaca",
  "İKİZLER JAPON OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Ferhan Demir",
  "İLER OTOMOTİV YEDEK PARÇA DAN.TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "İLKAY OTOMOTİV - İLKAY EYİÇALIŞ": "Ferhan Demir",
  "İLSEM OTOMOTİV SANAYİ VE TİC.LTD.ŞTİ.": "Mustafa Koçalı",
  "İMAGE CONTA OTOMOTİV SAN. VE TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "İMAJ AUTO OTO YEDEK PARÇA ÜRN.İÇ VE DIŞ TİC.LTD.ŞTİ.": "Cüneyt Baş",
  "İMAJ OPEL YEDEK PARÇA - MEHMET ERDEM": "Seçkin Ozan Akıllı",
  "İMZA OTO YEDEK PARÇA SAN.TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "İMZA OTO ÇIKMA - SABRİ BOYRAZ": "Ferhan Demir",
  "İMZA YEDEK PARÇA OTOMOTİV SAN.TİV.LTD.ŞTİ.": "Eren Ateş",
  "İNANÇ OTO YEDEK PARÇA - ZEKERİYA İNANÇ": "Sefa Akkan",
  "İNCEGÜL OTOMOTİV TURİZM İNŞ.İTH.İHR.SAN.VE TİC.LTD.ŞTİ.": "Onur Selvi",
  "İNCİ VOLKSWAGEN YEDEK PARÇA - HELİN KURT": "Serdar Parlakkan",
  "İNEGÖL BAYRAMOĞLU OTO YEDEK PARÇA TIC LTD ŞTI": "Engin Alaca",
  "İNEGÖL OTOPAR OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Engin Alaca",
  "İNKA KALIP METAL OTOMOTİV YEDEK PARÇA İNŞ.İÇ VE DIŞ TİC.LTD. ŞTİ.": "Erbay Atlı",
  "İPEK OTO KLİMA YEDEK PARÇA - BAYRAM İPEK": "Ali Osman Demir",
  "İS KAV NOKTA OTOMOTİV - DİLEM KAVUZLU": "Serdar Parlakkan",
  "İSLAMOĞLU BİLGİSAYAR İLET.OTO.NAK.İNŞ.TUR.GIDA PAZ.VE DIŞ TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "İSMAİL ATILGAN OTOMOTİV YEDEK PARÇA İTH.İHR.SAN.VE TİC.LTD.ŞTİ. / ŞAŞMAZ": "Eren Ateş",
  "İSMAİL GÜRBÜZ VE ORT.": "Ömer Kınalı",
  "İSMAİL HAKKI BAŞ-MÜYESSER İKE-BEYZA BAŞ-TALHA UBEYDULLAH BAŞ ADİ ORT.": "Ferhan Demir",
  "İSOCAR OTOMOTİV SAN.VE İTC.LTD.ŞTİ.": "Onur Selvi",
  "İSTANBUL TUNİNG - BAYRAM ENES YILDIRIM": "Ömer Kınalı",
  "İSTANBUL VOLKSWAGEN YEDEK PARÇA TİCARET YKL BİLİŞİM DANIŞMANLIK HİZMETLERİ - HÜSEYİN KAAN VOLKAN": "Ferhan Demir",
  "İVEDİK ÇAĞLAR OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Seçkin Ozan Akıllı",
  "İZMİR MOBİS OTOMOTİV YED.PARÇ.TİC. - ENGİN KORKMAZ /ŞUBE-3": "Sefa Akkan",
  "İZMİR MOBİS OTOMOTİV YEDEK PARÇA TİCARET - ENGİN KORKMAZ": "Sefa Akkan",
  "İZMİR MOBİS OTOMOTİV YEDEK PARÇA TİCARET - ENGİN KORKMAZ / ŞUBE": "Sefa Akkan",
  "İZMİR OPEL - SERDAR CANSESLİ": "Sefa Akkan",
  "İÇANADOLU RULMAN SANAYİ TİC.LTD.ŞTİ.": "Ömer Kınalı",
  "İŞİM OTOMOTİV YED.PAR.FİLO KİR.VE TİC.LTD.ŞTİ.": "Ferhan Demir",
  "ŞABAN NECAT İDİKUT - ESİN TİCARET": "Ferhan Demir",
  "ŞAFAK OTOMOTİV - AHMET AKKOYUN": "Eren Aykut",
  "ŞAHİN OTO - BİLAL ŞAHİN": "Ömer Kınalı",
  "ŞAHİNLER OTOMOTİV - İLKER ŞAHİN": "Engin Alaca",
  "ŞAHİNOĞLU OTOMOTİV - ARDA CAN ŞAHİN": "Mustafa Koçalı",
  "ŞANLI GROUP OTOMOTİV İNŞ.SAN.TİC.LTD.ŞTİ.": "Ali Osman Demir",
  "ŞANLI TUNİNG OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Eren Aykut",
  "ŞAŞMAZ OTO YED.PAR. - AHMET CAN ERYILMAZ": "Eren Ateş",
  "ŞAŞMAZ VOLKSWAGEN - YASİN KADİR DAŞDAN": "Eren Ateş",
  "ŞEKERCİ MOTORLU ARAÇLAR OTO YED.PAR.DIŞ TİC.İTH.İHR.SAN.VE TİC.LTD.ŞTİ.": "Alpaslan Değer",
  "ŞENDİNÇ OTOMOTİV SAN.İNŞ.TAAH.GIDA PAZ.LTD.ŞTİ.": "Alpaslan Değer",
  "ŞENER OTO YEDEK PARÇA SAN.VE TİC.A.Ş.": "Cüneyt Baş",
  "ŞENER OTOMOTİV NECMETTİN": "Ferhan Demir",
  "ŞENGÜN OTOMOTİV - SEYFETTİN ŞENGÜN": "Ferhan Demir",
  "ŞENOL OTOMOTİV - ŞENOL BERBER": "Cüneyt Baş",
  "ŞENOL OTOMOTİV - ŞENOL BERBER / USD": "Ferhan Demir",
  "ŞEYHANLI OTO YEDEK PARÇA - MUHAMMED DELİL ŞEYHANLIOĞLU": "Alpaslan Değer",
  "ŞİMŞEK MOTORLU ARAÇLAR OTOM.TUR.GID.ORM.ÜR.SAN.VE TİC.LTD.ŞTİ.": "Serdar Parlakkan",
  "ŞİMŞEK VOLKSWAGEN ORJ.ÇIKMA YED.PARÇA -  MÜCAHİT ŞİMŞEK": "Seçkin Ozan Akıllı",
  "ŞİMŞEKHAN YEDEK PARÇA OTOMOTİV SAN.VE TİC.LTD.ŞTİ.": "Alpaslan Değer",
  "ŞİMŞEKLER OTOM.YED.PAR.TEKS.GID.SAN.VE DIŞ TİC.LTD.ŞTİ.": "Ferhan Demir",
  "ŞİMŞEKTAŞ ENDÜSTRİYEL OTO YED.PAR.SAN.VE TİC.LTD.ŞTİ.": "Alpaslan Değer",
  "ŞİMŞEKTAŞ OTOMOTİV PAZARLAMA VE TİCARET A.Ş.": "Alpaslan Değer",
};

function normalize(s: string): string {
  return s
    .replace(/[İI]/g, "i")
    .replace(/Ğ/g, "g").replace(/Ü/g, "u").replace(/Ş/g, "s")
    .replace(/Ö/g, "o").replace(/Ç/g, "c")
    .toLowerCase()
    .replace(/ı/g, "i").replace(/ğ/g, "g").replace(/ü/g, "u")
    .replace(/ş/g, "s").replace(/ö/g, "o").replace(/ç/g, "c");
}

export function plasiyeriBul(musteriAdi: string): string | null {
  if (!musteriAdi || musteriAdi.trim().length < 3) return null;
  const aranan = normalize(musteriAdi.trim());

  const tam = Object.entries(MUSTERI_PLASIYER).find(([k]) => normalize(k) === aranan);
  if (tam) return tam[1];

  const partial = Object.entries(MUSTERI_PLASIYER).find(([k]) => normalize(k).includes(aranan));
  if (partial) return partial[1];

  return null;
}
